jitsi/jitsi-videobridge

- resources/install/debian/postinst
Prevents error messages in postinst which result in errors on package install/upgrade.
> Manipulates log files only if they exist.

- src/org/jitsi/videobridge/Channel.java
- src/org/jitsi/videobridge/Conference.java
- src/org/jitsi/videobridge/Content.java
- src/org/jitsi/videobridge/Videobridge.java
- src/org/jitsi/videobridge/stats/VideobridgeStatistics.java
Logs an estimated number of video streams (based on the number of channels and last N for each conference) in the log file as well as the statistics.
> Video stream count

- doc/last-n.md
- doc/using_statistics.md
Define xmpp message flow for connecting a focus to the Jitsi Videobridge to consume statistics stanzas.
> Add documentation on how to connect the focus to Jitsi Videobridge for pubsub statistics and lastN/Dominant speaker switching

- doc/newrelic.md
- src/main/java/org/jitsi/videobridge/metrics/MetricLoggingHandler.java
Add total number of endpoints to New Relic metrics and update documentation for readability and new metric
> Additional metrics for New Relic, documentation readability updates

- doc/rest-videobridge.md
A minimal commit, basically to test that my contributors agreement made it to Atlassian. There is more to come.
Please don't add me to the list of contributors, though.
> Remind to enable statistics in the REST interface documentation.

- resources/collect-dump-logs.sh
updated collect dump script to include heap dumps from OOM crashes if they are present in /tmp
> updated collect dump script to include heap dumps from OOM crashes

- src/main/java/org/jitsi/videobridge/simulcast/SimulcastEngine.java
- src/main/java/org/jitsi/videobridge/simulcast/SimulcastSender.java
- src/main/java/org/jitsi/videobridge/simulcast/SimulcastSenderManager.java
- src/main/java/org/jitsi/videobridge/simulcast/SimulcastStream.java
- src/main/java/org/jitsi/videobridge/simulcast/sendmodes/RewritingSendMode.java
- src/main/java/org/jitsi/videobridge/simulcast/sendmodes/SwitchingSendMode.java
This is a bunch of rudimentary source code maintenance commits really which fix javadocs, simplify and clean up source code, bring in consistency in naming.
> Renames simulcast match

- src/main/java/org/jitsi/videobridge/RtpChannel.java
Reverts jitsi/jitsi-videobridge#181
> Revert "Calls MediaStream#setTarget() before setConnector()."

- src/main/java/org/jitsi/videobridge/SctpConnection.java
Logs a message when an SCTP socket is accepted.
> Sets the data callback before the accept task is submitted.

- pom.xml
Updates libjitsi@1.0-20160420.145638-153 that attempts to fix a high CPU usage issue reported here http://lists.jitsi.org/pipermail/dev/2016-April/028151.html.
> Updates libjitsi@1.0-20160420.145638-153.

- src/main/java/org/jitsi/videobridge/LastNController.java
addresses https://github.com/jitsi/jitsi-videobridge/issues/198
> care about order when checking for active speaker changes

- doc/debugging.md
Adds documentation that describe some methods and techniques that can be used to debug the JVB.
> Adds a debugging.md

- doc/http.md
- src/main/java/org/jitsi/videobridge/rest/RESTBundleActivator.java
- src/main/java/org/jitsi/videobridge/rest/ssi/HttpServletResponseWrapper.java
- src/main/java/org/jitsi/videobridge/rest/ssi/SSIResourceHandler.java
In order to process a location and do the server-side includes. the location needs to be explicitly configured through a property. For example in order to configure the default welcome location you need to add:
org.jitsi.videobridge.rest.api.jetty.SSIResourceHandler.paths=/
> Adds ssi implementation for jetty.

- resources/mvn-exec.sh
Adds a startup script file for the Jitsi Videobridge that uses maven.
Maven is configured to run with a JVB-specific repository path. Multiple
required and optional arguments are supported.
> Adds maven based exec script.

- src/main/java/org/jitsi/videobridge/VideoChannel.java
Depends on and completes
https://github.com/jitsi/libjitsi/pull/179/commits/f6ad583cefec27df557b7283294d7e48dafc4883
> Moves all of the seqnum rewriting logic inside the OutputDataStreamImpl.

- src/main/java/org/jitsi/videobridge/LastNController.java
behavior.
idea here is to tweak a couple things to make it easier to override the specific logic of determining which endpoints should be in last-n (we do some different things here, so have a custom HighfiveLastNController to implement the logic we need).
> slight rework to LastNController to make it easier to override its

- pom.xml
- src/main/java/org/jitsi/videobridge/AudioChannel.java
- src/main/java/org/jitsi/videobridge/Endpoint.java
- src/main/java/org/jitsi/videobridge/LipSyncHack.java
- src/main/java/org/jitsi/videobridge/VideoChannel.java
Implements a hack to mitigate https://bugs.chromium.org/p/chromium/issues/detail?id=403710. The hack sends black VP8 key frames so that audio playback is unstuck at the client.
UPDATE: This PR depends on https://github.com/jitsi/libjitsi/pull/181. Please do not merge this before the LJ pr is merged. Also, the pom.xml file needs to be updated before merging this.
> Implements LS hack.

- src/main/java/org/jitsi/videobridge/transform/RtxTransformer.java
Issue reported by George Politis.
> Only create Random and call nextInt if necessary.

- doc/statistics.md
- src/main/java/org/jitsi/videobridge/RtpChannel.java
> Update the statistics documentation

- pom.xml
- src/main/java/org/jitsi/videobridge/Content.java
- src/main/java/org/jitsi/videobridge/VideoChannel.java
- src/main/java/org/jitsi/videobridge/Videobridge.java
- src/main/java/org/jitsi/videobridge/xmpp/ComponentImpl.java
- src/test/java/org/jitsi/videobridge/FocusControlTest.java
The purpose if this PR is to make JVB return meaningful error when usually it would have returned "feature-not-implemented" error.
> Return error details

- doc/callstats.md
- pom.xml
- src/main/java/org/jitsi/videobridge/stats/CallStatsIOTransport.java
- src/main/java/org/jitsi/videobridge/stats/callstats/TokenGenerator.java
Implements jwt authentication for callstats.
> Callstats jwt authentication.

- src/main/java/org/jitsi/videobridge/Channel.java
- src/main/java/org/jitsi/videobridge/Conference.java
- src/main/java/org/jitsi/videobridge/Videobridge.java
Guys, i am absolutely new to Java, this pull request is just a reference to what i was talking about in issue that i have opened: https://github.com/jitsi/jitsi-videobridge/issues/279. Please feel free to modify as needed.
> Fixe for issue https://github.com/jitsi/jitsi-videobridge/issues/279

- build.xml
- openfire/changelog.html
- openfire/plugin.xml
- openfire/src/i18n/jitsivideobridge_i18n.properties
- openfire/src/java/org/jitsi/videobridge/openfire/JvbOpenfireBundleConfig.java
- openfire/src/java/org/jitsi/videobridge/openfire/PluginImpl.java
- openfire/src/web/jitsi-videobridge.jsp
The changes in this pull request address various issues (including, but not limited to #178) with the Openfire plugin, that is part of the Jitsi-videobridge project.
I've tried to address each issue (which range from bugs to minor improvement) in separate and concise commits.
> Addressing various Openfire plugin issues

- src/main/java/org/jitsi/videobridge/LipSyncHack.java
Sends 3 waves of black key frames, each separated by 1 second, to make
sure that at least one black key frame reaches the receiver after
signaling has propagated.
> fix(ls-hack): Sends 3 waves of black key frames.

- resources/install/debian/control
- resources/install/debian/postinst
- resources/install/debian/templates
Please do not merge.
Work in progress decoupling jitsi-meet components. Introducing a new jitsi-meet meta package depending on particular component versions.
> Updates debian packaging.

- doc/statistics.md
- src/main/java/org/jitsi/videobridge/Conference.java
- src/main/java/org/jitsi/videobridge/Endpoint.java
- src/main/java/org/jitsi/videobridge/Videobridge.java
- src/main/java/org/jitsi/videobridge/stats/VideobridgeStatistics.java
> stats: Adds the number of messages sent and received over data channels

- pom.xml
- src/main/java/org/jitsi/videobridge/IceUdpTransportManager.java
- src/main/java/org/jitsi/videobridge/Main.java
selecting the candidate pairs to be kept alive.
> feat: Implements different strategies for

- pom.xml
- src/main/java/org/jitsi/videobridge/AudioChannel.java
- src/main/java/org/jitsi/videobridge/Endpoint.java
- src/main/java/org/jitsi/videobridge/LipSyncHack.java
- src/main/java/org/jitsi/videobridge/VideoChannel.java
- src/main/java/org/jitsi/videobridge/Videobridge.java
- src/main/java/org/jitsi/videobridge/transform/RtpChannelTransformEngine.java
If the lip sync hack is enabled, always send black VP8 kfs before the
start of a stream.
> fix: Prepend the video stream with black VP8 kfs.

- src/main/java/org/jitsi/videobridge/Endpoint.java
- src/main/java/org/jitsi/videobridge/simulcast/SimulcastSender.java
- src/main/java/org/jitsi/videobridge/simulcast/SimulcastSenderManager.java
Removes some unnecessary synchronized blocks.
> fix: Reduces synchronization.

- resources/collect-dump-logs.sh
check for and archive up the crash dumps from /var/crash if they exist for our user in the past 20 minutes
> collect crash dumps during collect-dump-logs.sh

- pom.xml
> Removes unneeded dependency.

- resources/install/debian/postinst
> cleanup: Removes dead code.

- src/main/java/org/jitsi/videobridge/Conference.java
- src/main/java/org/jitsi/videobridge/Content.java
- src/main/java/org/jitsi/videobridge/EndpointRecorder.java
- src/main/java/org/jitsi/videobridge/RecorderEventHandlerImpl.java
- src/main/java/org/jitsi/videobridge/RtpChannel.java
- src/main/java/org/jitsi/videobridge/Videobridge.java
- src/main/java/org/jitsi/videobridge/rest/JSONDeserializer.java
- src/main/java/org/jitsi/videobridge/rest/JSONSerializer.java
This reverts commit 6a3129d46a36f4e5592a0f58b4456fadecae9741.
> Revert "cleanup: Removes the recording functionality."

- src/main/java/org/jitsi/videobridge/rest/JSONDeserializer.java
- src/main/java/org/jitsi/videobridge/rest/JSONSerializer.java
The option got axed, there is nothing to handle now.
> cleanup: remove code handling simulcast mode

- pom.xml
- src/main/java/org/jitsi/videobridge/cc/BitrateController.java
- src/main/java/org/jitsi/videobridge/cc/SimulcastController.java
Depends on https://github.com/jitsi/libjitsi/pull/296
> Temporal scalability filtering fixes

- src/main/java/org/jitsi/videobridge/LipSyncHack.java
Chrome 57 changed the default payload types (e.g. previously it was 100 for VP8 and now it's 96). We're still using the old payload types and now Chrome seems to not register the associated payload type for VP8 RTX which breaks retransmissions. The workaround is to use the new payload type defaults that Chrome 57 is using, so the LS hack needs to dynamically discover the VP8 payload type and not always assume it's 100.
> fix(ls-hack): Supports dynamic PT for VP8.

- src/main/java/org/jitsi/videobridge/IceUdpTransportManager.java
- src/main/java/org/jitsi/videobridge/RtpChannel.java
- src/main/java/org/jitsi/videobridge/TransportManager.java
This is #428 rebased on top of master.
> feat: Adds a TransportCCEngine to the transport manager.

- src/main/java/org/jitsi/videobridge/Conference.java
- src/main/java/org/jitsi/videobridge/Endpoint.java
- src/main/java/org/jitsi/videobridge/EndpointMessageTransport.java
- src/main/java/org/jitsi/videobridge/VideoChannel.java
Extracts the code for handling sending and receiving messages for an Endpoint into EndpointMessageTransport in preparation for the introduction of a new underlying transport (web sockets).
> Refactors the Endpoint class

- doc/rest.md
- doc/statistics.md
- pom.xml
- src/main/java/org/jitsi/videobridge/Conference.java
- src/main/java/org/jitsi/videobridge/Endpoint.java
- src/main/java/org/jitsi/videobridge/EndpointConnectionStatus.java
- src/main/java/org/jitsi/videobridge/EndpointMessageTransport.java
- src/main/java/org/jitsi/videobridge/IceUdpTransportManager.java
- src/main/java/org/jitsi/videobridge/VideoChannel.java
- src/main/java/org/jitsi/videobridge/Videobridge.java
- src/main/java/org/jitsi/videobridge/cc/BitrateController.java
- src/main/java/org/jitsi/videobridge/rest/ColibriWebSocket.java
- src/main/java/org/jitsi/videobridge/rest/ColibriWebSocketService.java
- src/main/java/org/jitsi/videobridge/rest/ColibriWebSocketServlet.java
- src/main/java/org/jitsi/videobridge/rest/PublicRESTBundleActivator.java
- src/main/java/org/jitsi/videobridge/stats/VideobridgeStatistics.java
Supports WebSockets as an alternative transport for COLIBRI messages (i.e. an alternative to WebRTC data channels).
> Colibri web sockets

- src/main/java/org/jitsi/videobridge/Videobridge.java
when an authorized source pattern is given (the case when
(options & OPTION_ALLOW_NO_FOCUS) != 0, but also
authorizedSourcePattern != null && focus != null).
> fix: Fixes a failure to accept COLIBRI requests via REST

- pom.xml
Fixes leak of file descriptors.
> mvn: Updates ice4j.

- src/main/java/org/jitsi/videobridge/cc/BitrateController.java
Other than being a useful feature, this resolves an issue where the JVB
does not forward a FF stream in a multi-party call. FF signals multiple
local tracks (because of unified plan). The current JVB code assumes a
single track per endpoint, so it only shapes the traffic for the first
video track. So, if the send track from FF happens to be in the end of
the tracks list, it never gets forwarded.
> feat: Implements bitrate allocation for multiple tracks per endpoint.

- pom.xml
- src/main/java/org/jitsi/videobridge/cc/BandwidthProbing.java
- src/main/java/org/jitsi/videobridge/cc/BitrateController.java
- src/main/java/org/jitsi/videobridge/cc/SimulcastController.java
- src/main/java/org/jitsi/videobridge/osgi/JvbBundleConfig.java
- src/main/java/org/jitsi/videobridge/xmpp/MediaStreamTrackFactory.java
Depends on https://github.com/jitsi/libjitsi/pull/308
> High fps allocation for on-stage participants.

- src/main/java/org/jitsi/videobridge/cc/BitrateController.java
- don't forward any thumbnails unless the on-stage speaker has 360p.
- reduces the changes in the number of thumbnails that are forwarded
> feat: Improvements to the bitrate allocation algorithm.

- pom.xml
- src/main/java/org/jitsi/videobridge/osgi/JvbBundleConfig.java
to ignore trailing zeroes in USERNAME attributes
> Configure ice4j

- src/main/java/org/jitsi/videobridge/cc/SimulcastController.java
This PR contains fixes for supporting Microsoft Edge. See message of each commit for more details.
> WIP: Fixes for supporting Microsoft Edge

- doc/rest-colibri.md
There were an issue with how the table was displayed. This PR fixes it.
> Fix formatting issue

- src/main/java/org/jitsi/videobridge/AudioChannel.java
- src/main/java/org/jitsi/videobridge/Content.java
- src/main/java/org/jitsi/videobridge/LipSyncHack.java
- src/main/java/org/jitsi/videobridge/RtpChannel.java
- src/main/java/org/jitsi/videobridge/VideoChannel.java
- src/main/java/org/jitsi/videobridge/cc/BitrateController.java
going any further requires changing the RtpTranslator#WriteFilter interface in libjitsi which involves lots of changes, so will save those for another PR
> Move the RawPacket API further up the accept/translatorWillWrite chain

- pom.xml
- src/main/java/org/jitsi/videobridge/cc/SimulcastController.java
relies on https://github.com/jitsi/libjitsi/pull/349#issuecomment-319764527
> minor/cosmetic refactoring in SimulcastController

- src/main/java/org/jitsi/videobridge/cc/SimulcastController.java
fix an issue with downscaling where we wouldn't switch to a quality that was lower than the target index even if the target index relied on it
> fix a downscaling issue

- doc/rest-colibri.md
This PR just cleans up the rest-colibri document.
> Tidy up REST document

- src/main/java/org/jitsi/videobridge/osgi/JvbBundleConfig.java
This reverts commit ed4327a1e42090e9e1c1bc4a4371a48707138fa7.
> Revert "Configure ice4j "

- pom.xml
- src/main/java/org/jitsi/videobridge/RtpChannel.java
- src/main/java/org/jitsi/videobridge/VideoChannel.java
Depends on https://github.com/jitsi/libjitsi/pull/361
> feat: Implements send-side bandwidth estimations.

- src/main/java/org/jitsi/videobridge/Channel.java
- src/main/java/org/jitsi/videobridge/Videobridge.java
> Sctp expire fixes

- pom.xml
> mvn: Set the source and target level to 1.8.

- pom.xml
- src/main/java/org/jitsi/videobridge/cc/BitrateController.java
- src/main/java/org/jitsi/videobridge/xmpp/MediaStreamTrackFactory.java
- src/test/java/org/jitsi/videobridge/xmpp/MediaStreamTrackFactoryTest.java
depends on https://github.com/jitsi/libjitsi/pull/385
SQUASH
> Encoding secondary ssrc

- src/main/java/org/jitsi/videobridge/RtpChannel.java
- src/main/java/org/jitsi/videobridge/xmpp/MediaStreamTrackFactory.java
> Fix NullPointerException when user has no tracks open

- src/main/java/org/jitsi/videobridge/RtpChannel.java
- src/main/java/org/jitsi/videobridge/cc/BitrateController.java
- src/main/java/org/jitsi/videobridge/xmpp/MediaStreamTrackFactory.java
- src/test/java/org/jitsi/videobridge/xmpp/MediaStreamTrackFactoryTest.java
All credit goes to @bgrozev here, I just added a unit test on top of his fix for the issue.  original PR was here: https://github.com/jitsi/jitsi-videobridge/pull/590/
> Fix groupless ssrcs

- pom.xml
- src/main/java/org/jitsi/videobridge/Conference.java
- src/main/java/org/jitsi/videobridge/IceUdpTransportManager.java
- src/main/java/org/jitsi/videobridge/RtpChannel.java
This PR enables logs correlation on the bridge. It also updates libjitsi@1.0-20180117.223511-333.
> feat: Passes the logging id to the media stream.

- src/main/java/org/jitsi/videobridge/cc/BitrateController.java
This PR is not ready, please don't merge yet.
> WIP: Makes the on-stage participant video suspend option configurable.

- src/main/java/org/jitsi/videobridge/VideobridgeExpireThread.java
blocking for a prolonged period of time and resulting in conferences
failing to be expired.
> fix: Tries to fix a problem with VideobridgeExpireThread

- src/main/java/org/jitsi/videobridge/Conference.java
- src/main/java/org/jitsi/videobridge/Videobridge.java
mentioned in the request in a COLIBRI response.
> feat(colibri): Only includes channel-bundles

- src/main/java/org/jitsi/videobridge/cc/BitrateController.java
- src/main/java/org/jitsi/videobridge/cc/SimulcastController.java
Introduced in 5b789d96018d53c13befff652288f7764bfe994d.
> fix: Fixes regression in simulcast controller.

- pom.xml
Updates libjitsi to contain this fix: https://github.com/jitsi/libjitsi/pull/424
> Update libjitsi (Fix getting primary block of RED packets)

- src/main/java/org/jitsi/videobridge/VideoChannel.java
This augments and supersedes https://github.com/jitsi/jitsi-videobridge/pull/618.
> Update the bitrate controller when the stream starts v2

- pom.xml
- src/main/java/org/jitsi/videobridge/Videobridge.java
- src/main/java/org/jitsi/videobridge/health/Health.java
- src/test/java/org/jitsi/videobridge/BridgeShutdownTest.java
- src/test/java/org/jitsi/videobridge/FocusControlTest.java
- src/test/java/org/jitsi/videobridge/Util.java
Requests from XMPP and REST return cached results.
> feat: Performs health checks in a separate thread.

- src/main/java/org/jitsi/videobridge/EndpointConnectionStatus.java
The EndpointConnectionStatus stores 'inactive' status even for Endpoints that have expired in order to show the disconnected status in Jitsi-Meet after the channels could have been expired by Jicofo, but the person stayed in the room.
The current cleanup logic will remove it only after the parent conference has expired. That is causing problem in case the channels are expired and re-created for Endpoints within the same conference. This commit adds an extra check for a new, unexpired Endpoint in the conference which is not the instance stored in the 'inactiveEndpoints' list.
> fix(EndpointConnectionStatus): leaking expired Endpoints

- pom.xml
- src/main/java/org/jitsi/videobridge/RtpChannelDatagramFilter.java
- src/main/java/org/jitsi/videobridge/cc/GenericAdaptiveTrackProjectionContext.java
Depends on https://github.com/jitsi/libjitsi/pull/462
> Adapts to LJ.

- src/main/java/org/jitsi/videobridge/cc/AdaptiveTrackProjection.java
- src/main/java/org/jitsi/videobridge/cc/AdaptiveTrackProjectionContext.java
- src/main/java/org/jitsi/videobridge/cc/GenericAdaptiveTrackProjectionContext.java
- src/main/java/org/jitsi/videobridge/cc/vp8/VP8AdaptiveTrackProjectionContext.java
- src/main/java/org/jitsi/videobridge/cc/vp8/VP8QualityFilter.java
This is not the complete implementation for adding simulcast support for screensharing, but it's an improvement over what we have today and can be merged on its own. There will be a supplemental PR that completes this work.
> fix: Partially handles screen-sharing simulcast.

- src/main/java/org/jitsi/videobridge/DtlsTransport.java
- src/main/java/org/jitsi/videobridge/Endpoint.java
- src/main/java/org/jitsi/videobridge/shim/VideobridgeShim.java
> DTLS 1.2/DTLS server role support/BC 1.61

- src/main/java/org/jitsi/videobridge/util/PayloadTypeUtil.java
Depends on https://github.com/jitsi/jitsi-media-transform/pull/47
> adds rtcp feedback information to new PayloadType instances

- src/main/java/org/jitsi/videobridge/Conference.java
- src/main/java/org/jitsi/videobridge/cc/BitrateController.java
> Fixes build

- pom.xml
- resources/inspect_rtp_vp8_rewrite.py
- resources/link-conditioner.sh
- src/main/java/org/jitsi/videobridge/AbstractEndpoint.java
- src/main/java/org/jitsi/videobridge/Endpoint.java
- src/main/java/org/jitsi/videobridge/IceTransport.java
- src/main/java/org/jitsi/videobridge/cc/AdaptiveTrackProjection.java
- src/main/java/org/jitsi/videobridge/cc/BitrateController.java
- src/main/java/org/jitsi/videobridge/cc/vp8/VP8AdaptiveTrackProjectionContext.java
- src/main/java/org/jitsi/videobridge/cc/vp8/VP8FrameProjection.java
- src/main/java/org/jitsi/videobridge/cc/vp8/VP8QualityFilter.java
- src/main/java/org/jitsi/videobridge/octo/OctoEndpoint.java
depends on https://github.com/jitsi/jitsi-media-transform/pull/65
> wip: fixes various adaptivity regressions in the new bridge

- pom.xml
- src/main/java/org/jitsi/videobridge/DtlsTransport.java
- src/main/java/org/jitsi/videobridge/EndpointMessageTransport.java
- src/main/java/org/jitsi/videobridge/cc/vp8/VP8AdaptiveTrackProjectionContext.java
log when the role is not set at start time
> Simplify, adapt to JMT,

- resources/timeseries-cli.py
- src/main/java/org/jitsi/videobridge/cc/BitrateController.java
- src/main/java/org/jitsi/videobridge/xmpp/MediaStreamTrackFactory.java
depends on https://github.com/jitsi/jitsi-media-transform/pull/79
> adapts to jmt changes

- pom.xml
- src/main/java/org/jitsi/videobridge/DtlsTransport.java
- src/main/java/org/jitsi/videobridge/Videobridge.java
- src/main/java/org/jitsi/videobridge/octo/OctoTransceiver.java
- src/main/java/org/jitsi/videobridge/rest/StatisticsRequestHandler.java
Keep track of dropped packets and expose it at /colibri/stats/queue
> Increase queue sizes to 1024.

- pom.xml
- src/main/java/org/jitsi/videobridge/AbstractEndpoint.java
- src/main/java/org/jitsi/videobridge/Conference.java
- src/main/java/org/jitsi/videobridge/Endpoint.java
- src/main/java/org/jitsi/videobridge/cc/AdaptiveTrackProjection.java
- src/main/java/org/jitsi/videobridge/cc/BitrateController.java
- src/main/java/org/jitsi/videobridge/octo/OctoEndpoint.java
- src/main/java/org/jitsi/videobridge/octo/OctoTentacle.java
depends on: https://github.com/jitsi/jitsi-media-transform/pull/87
implements keyframe requests for foreign endpoints; keyframes can be requested by the bitrate controller
> implements keyframe requests to foreign endpoints

- src/main/java/org/jitsi/videobridge/Endpoint.java
```
JVB 2019-06-12 11:40:56.986 INFO: [159] org.ice4j.ice.Agent.log() Gathering candidates for component stream-290b6785.RTP. Local ufrag 9orst1dd5nrc8q
JVB 2019-06-12 11:40:56.986 INFO: [83] org.ice4j.ice.Agent.log() Gathering candidates for component stream-290b6785.RTP. Local ufrag 1hc4b1dd5nrc8q
JVB 2019-06-12 11:40:56.987 INFO: [84] org.ice4j.ice.Agent.log() Gathering candidates for component stream-290b6785.RTP. Local ufrag ceq2f1dd5nrc8r
```
> fix: Fixes a bug with multiple transport managers being created.

- pom.xml
- resources/timeseries-cli.py
- src/main/java/org/jitsi/videobridge/Conference.java
- src/main/java/org/jitsi/videobridge/DtlsTransport.java
- src/main/java/org/jitsi/videobridge/EncodingsManager.java
- src/main/java/org/jitsi/videobridge/Endpoint.java
- src/main/java/org/jitsi/videobridge/cc/BandwidthProbing.java
- src/main/java/org/jitsi/videobridge/cc/BitrateController.java
- src/main/java/org/jitsi/videobridge/shim/ChannelShim.java
Depends on https://github.com/jitsi/jitsi-utils/pull/5
> various fixes for bandwidth estimations/distribution

- pom.xml
- src/main/java/org/jitsi/videobridge/DtlsTransport.java
- src/main/java/org/jitsi/videobridge/Videobridge.java
- src/main/java/org/jitsi/videobridge/rest/DebugRequestHandler.java
- src/main/java/org/jitsi/videobridge/rest/StatisticsRequestHandler.java
- src/main/java/org/jitsi/videobridge/stats/PacketTransitTime.java
relies on https://github.com/jitsi/jitsi-media-transform/pull/95
> Packet delay

- src/main/java/org/jitsi/videobridge/DtlsTransport.java
- src/main/java/org/jitsi/videobridge/Videobridge.java
- src/main/java/org/jitsi/videobridge/rest/StatisticsRequestHandler.java
- src/main/java/org/jitsi/videobridge/stats/DoubleAverage.java
- src/main/java/org/jitsi/videobridge/stats/PacketTransitStats.java
relies on https://github.com/jitsi/jitsi-media-transform/pull/99
> Track jitter introduced by the bridge

- pom.xml
libjitsi and jitsi-media-transform.
> Updates the versions of jitsi-utils, jitsi-rtp,

- build.xml
- pom.xml
- resources/install/debian/changelog.tmpl
- resources/install/debian/control
- resources/install/debian/jitsi-videobridge2.service
- resources/install/debian/rules
> Updates debian packaging and changing the name of the package

- src/main/java/org/jitsi/videobridge/Videobridge.java
- src/test/java/org/jitsi/videobridge/BridgeShutdownTest.java
ShutdownService now comes from jicoco (instead of the ui-service bundle)
and it is used by jicoco.
> Uses ShutdownService again.

- pom.xml
- src/main/java/org/jitsi/videobridge/Endpoint.java
adapts to https://github.com/jitsi/jitsi-media-transform/pull/111/files
> support local vs remote source associations

- pom.xml
- src/main/java/org/jitsi/videobridge/eventadmin/callstats/ConferencePeriodicRunnable.java
This depends on jitsi/jitsi-media-transform#112 and jitsi/jitsi-stats#8
> Brings back callstats per-endpoint reporting.

- pom.xml
- src/main/java/org/jitsi/videobridge/AbstractEndpoint.java
- src/main/java/org/jitsi/videobridge/AbstractEndpointMessageTransport.java
- src/main/java/org/jitsi/videobridge/Conference.java
- src/main/java/org/jitsi/videobridge/ConferenceSpeechActivity.java
- src/main/java/org/jitsi/videobridge/DtlsTransport.java
- src/main/java/org/jitsi/videobridge/Endpoint.java
- src/main/java/org/jitsi/videobridge/EndpointMessageTransport.java
- src/main/java/org/jitsi/videobridge/IceTransport.java
- src/main/java/org/jitsi/videobridge/Videobridge.java
- src/main/java/org/jitsi/videobridge/octo/OctoEndpoint.java
- src/main/java/org/jitsi/videobridge/octo/OctoEndpointMessageTransport.java
- src/main/java/org/jitsi/videobridge/octo/OctoEndpoints.java
- src/main/java/org/jitsi/videobridge/octo/OctoTentacle.java
- src/main/java/org/jitsi/videobridge/octo/OctoTransceiver.java
- src/main/java/org/jitsi/videobridge/util/ExpireableImpl.java
jvb changes to adapt to the new logger in https://github.com/jitsi/jitsi-utils/pull/11
> Logging v2

- pom.xml
- src/main/java/org/jitsi/videobridge/AbstractEndpoint.java
- src/main/java/org/jitsi/videobridge/Conference.java
- src/main/java/org/jitsi/videobridge/Endpoint.java
- src/main/java/org/jitsi/videobridge/octo/OctoEndpoint.java
- src/main/java/org/jitsi/videobridge/octo/OctoTentacle.java
second take on pre-emptive keyframes after all the stream information store work. note that this is built on top of the logging changes, so all those commits are here. will merge this after that stuff has gone in.
> Preemptive keyframes 2

- src/main/java/org/jitsi/videobridge/Conference.java
- src/main/java/org/jitsi/videobridge/ConferenceSpeechActivity.java
Fixed several null pointer exception observed during upgrade to JVB 2.0.
> Fixed several NullPointerExceptions

- src/main/java/org/jitsi/videobridge/osgi/BundleConfig.java
- src/main/java/org/jitsi/videobridge/xmpp/MediaStreamTrackFactory.java
It was mistakenly disabled in #901
> fix: Re-enables SVC.

- pom.xml
- src/main/java/org/jitsi/videobridge/IceTransport.java
(previous PR for this [here](https://github.com/jitsi/jitsi-videobridge/pull/915))
> Adapt to changes in ice4j to use the jitsi-utils logger

- pom.xml
Checks whether the incoming iq is from the control room we have.
> Updates jicoco to latest.

- pom.xml
- src/main/java/org/jitsi/videobridge/Conference.java
- src/main/java/org/jitsi/videobridge/Endpoint.java
- src/main/java/org/jitsi/videobridge/cc/BandwidthProbing.java
Update videobridge following the jitsi-media-transform bandwidth estimation rework.
This depends on https://github.com/jitsi/jitsi-media-transform/pull/130 (and thus indirectly https://github.com/jitsi/jitsi-rtp/pull/46.)
> Changes following jitsi-media-transform bandwidth estimation rework.

- src/main/java/org/jitsi/videobridge/Endpoint.java
before this, if an endpoint was allocated but never
started ice, it would never be expired as, if an ep has never had
activity, we waited for ice to fail...but you can't fail ice if you
never start ice...
> add an extra layer of tiimeout detection for endpoints

- pom.xml
this gets the SR fix and the logging around 'missing packet detail'
> update jmt version

- src/main/java/org/jitsi/videobridge/Endpoint.java
- src/main/java/org/jitsi/videobridge/shim/ChannelShim.java
the directions we check here are from the bridge's perspective, not the clients
> fix allowsReceivingMediaCheck

- pom.xml
This update gets the changes to move the configuration service to jitsi-utils
> update jitsi-utils & jicoco

- pom.xml
- src/main/java/org/jitsi/videobridge/AbstractEndpoint.java
- src/main/java/org/jitsi/videobridge/Endpoint.java
- src/main/java/org/jitsi/videobridge/EndpointConnectionStatus.java
Changed the checking endpoint activity logic according to https://github.com/jitsi/jitsi-media-transform/pull/154
> Correct method for checking endpoint activity

- CONFIG.md
- src/main/java/org/jitsi/videobridge/cc/BitrateController.java
- src/main/kotlin/org/jitsi/videobridge/cc/config/BitrateControllerConfig.kt
- src/main/resources/reference.conf
This is built on top of the changes [here](https://github.com/jitsi/jitsi-videobridge/pull/991), so can ignore all but the last commit (but this will need a rebase before merging)
> Port bitrate controller config props

- CONFIG.md
- src/main/java/org/jitsi/videobridge/cc/BandwidthProbing.java
- src/main/kotlin/org/jitsi/videobridge/cc/config/BandwidthProbingConfig.kt
- src/main/resources/reference.conf
I referred to the props differently here: did a static import instead of using the class.  It's nice that it shortens things a bit, and I think the import still makes it clear.  If we like this, then can fix the other ones at some point.
> port bandwidth probing config

- pom.xml
Pulling in recent improvements.
> Bump jmt and rtp maven versions.

- src/main/java/org/jitsi/videobridge/cc/AdaptiveTrackProjection.java
When AdaptiveTrackProjection.getSource() (which uses a weak ref) returns null.
> Prevent null pointer exception.

- pom.xml
Picks up enhanced SRTP statistics.
> Bump jmt version.

- pom.xml
> Update jmt again.

- pom.xml
For RTP and VP8 packet optimizations.
> Bump jitsi-utils, rtp, and jmt versions.

- src/main/java/org/jitsi/videobridge/DtlsTransport.java
- src/main/java/org/jitsi/videobridge/Endpoint.java
- src/main/java/org/jitsi/videobridge/sctp/SctpManager.java
Marking this as a draft for now, as I plan on adding some comments to each fix about things we might want to change before merging.
> Address some buffer issues

- pom.xml
- src/main/java/org/jitsi/videobridge/DtlsTransport.java
- src/main/java/org/jitsi/videobridge/Endpoint.java
- src/main/java/org/jitsi/videobridge/octo/OctoTentacle.java
- src/main/java/org/jitsi/videobridge/octo/OctoTransceiver.java
- src/main/java/org/jitsi/videobridge/rest/root/colibri/debug/Debug.java
- src/main/java/org/jitsi/videobridge/rest/root/colibri/debug/DebugFeatures.java
The JVB change corresponding to https://github.com/jitsi/jitsi-media-transform/pull/201.
> Node tracking: jvb changes.

- src/main/java/org/jitsi/videobridge/cc/vp8/VP8AdaptiveTrackProjectionContext.java
- src/main/java/org/jitsi/videobridge/cc/vp8/VP8FrameMap.java
- src/test/java/org/jitsi/videobridge/cc/vp8/VP8AdaptiveTrackProjectionTest.java
Note this incorporates https://github.com/jitsi/jitsi-videobridge/pull/1081 as well.
> Handle frame projection when there is a large jump/dropout in packets.

- pom.xml
- src/main/java/org/jitsi/videobridge/Videobridge.java
- src/main/java/org/jitsi/videobridge/rest/root/colibri/debug/Debug.java
- src/main/java/org/jitsi/videobridge/rest/root/colibri/debug/DebugFeatures.java
- src/main/java/org/jitsi/videobridge/stats/PacketTransitStats.java
- src/main/java/org/jitsi/videobridge/xmpp/XmppCommon.java
Depends on jitsi/jitsi-utils#45 and jitsi/jitsi-media-transform#217
> Keep track of the processing time for XMPP requests.

- src/main/java/org/jitsi/videobridge/Endpoint.java
This PR is attempt to allow scenario described [here](https://github.com/jitsi/jitsi-videobridge/pull/972#issuecomment-569266366).
An implementation is my interpretation of [@bbaldino suggestion](https://github.com/jitsi/jitsi-videobridge/pull/972#issuecomment-569309700)
> Added method to update endpoint media direction.

- pom.xml
> Bump RTP version.

- pom.xml
Updates jicoco to 1.1-20-ge4ade96.
> deps: updates jicoco to bring in MUC XMPP port option

- doc/datachannel-communication.md
You wanted a title, not a comment, now, did you? ;-)
> fix titles

- debian/po/templates.pot
- debian/templates
> Fix typo in installation message

- pom.xml
- src/main/java/org/jitsi/videobridge/Endpoint.java
- src/main/java/org/jitsi/videobridge/shim/ChannelShim.java
supported for audio only, currently
depends on https://github.com/jitsi/jitsi-media-transform/pull/249
> allow muting via setting the direction a channel

- pom.xml
- src/main/java/org/jitsi/videobridge/DtlsTransport.java
- src/main/java/org/jitsi/videobridge/octo/OctoRelay.java
Depends on https://github.com/jitsi/jitsi-utils/pull/53 and https://github.com/jitsi/jitsi-media-transform/pull/251.
> Fix various buffer pool leaks

- pom.xml
- src/main/kotlin/org/jitsi/videobridge/transport/ice/IceTransport.kt
Rather than sun.net.util.IPAddressUtil.  Fixes Java 11 build.
> Use Guava InetAddresses to determine if something is a literal IP address.

- doc/callstats.md
> adding conferenceIDPrefix to docs

- README.md
- debian/init.d
- debian/jitsi-videobridge2.service
- resources/mvn-exec.sh
Closes #1237 (thanks to #1266).
> remove residual use of options obsoleted by #1266

- .github/workflows/maven.yml
> CI: cache local Maven repository

- jvb-api/jvb-api-client/pom.xml
- jvb-api/jvb-api-common/pom.xml
- jvb-api/jvb-api-server/pom.xml
- jvb_pom.xml
- pom.xml
Because they need to be edited by the PR testing script.
> Use maven dependencyManagement for jitsi dependencies.

- pom.xml
https://github.com/jitsi/jicoco/pull/87
> fix: Fixes a case where jvb will stop reconnecting to the muc.

- .editorconfig
- jvb-api/jvb-api-client/src/test/kotlin/org/jitsi/videobridge/api/util/WebSocketClientTest.kt
- jvb-api/jvb-api-client/src/test/kotlin/org/jitsi/videobridge/api/util/XmppWebSocketClientTest.kt
- src/main/kotlin/org/jitsi/videobridge/octo/OctoRelayService.kt
- src/main/kotlin/org/jitsi/videobridge/stats/config/StatsManagerBundleActivatorConfig.kt
- src/main/kotlin/org/jitsi/videobridge/transport/dtls/DtlsTransport.kt
- src/main/kotlin/org/jitsi/videobridge/transport/octo/BridgeOctoTransport.kt
- src/main/kotlin/org/jitsi/videobridge/xmpp/config/XmppClientConnectionConfig.kt
We'll have to use something else for the java code
> Enforce line length of 120, fix errors (kotlin only)

- resources/jvb.sh
Enable definition of garbage collection via a dedicated env variable VIDEOBRIDGE_GC_TYPE
> + Env variable that defines GC type

- pom.xml
Retry login if already logged in. https://github.com/jitsi/jicoco/pull/88
> Chore: Bump jicoco.

- jvb/src/main/java/org/jitsi/videobridge/rest/RESTBundleActivator.java
- jvb/src/main/java/org/jitsi/videobridge/websocket/WebSocketBundleActivator.java
- pom.xml
See https://github.com/jitsi/jicoco/pull/99
> adapt to change in AbstractJettyBundleActivator

- pom.xml
(Rather than once per packet reported on by feedback.)
Updates jmt.
> FEAT: Optimize bwe calculations: only calculate bwe once per feedback message.

- pom.xml
Make the set of supported SRTP protection profiles a configuration option.
Updates jmt.
> Feature: Support GCM for DTLS/SRTP.

- pom.xml
Also feat: Add debugging config option to simulate packet loss.
(JMT update)
> Feat: Avoid benchmarking srtp engines; make srtp engine configurable.

- jvb/src/main/kotlin/org/jitsi/videobridge/octo/config/OctoRtpSender.kt
- pom.xml
This is the counterpart to https://github.com/jitsi/jitsi-media-transform/pull/237.
Adapt to JMT changes.
> BWE and Transport-CC stats enhancements.

- jvb/src/main/kotlin/org/jitsi/videobridge/Main.kt
This was a regression from https://github.com/jitsi/jitsi-videobridge/pull/1468
> set the websocket service instance in the singleton

- jvb/src/main/java/org/jitsi/videobridge/cc/BitrateController.java
- ref: Move inner classes below methods.
- ref: Formatting (use line length 120).
> ref: Improve formatting in BitrateController.

- jvb/src/main/java/org/jitsi/videobridge/cc/BitrateController.java
- jvb/src/test/kotlin/org/jitsi/videobridge/cc/BitrateControllerTest.kt
Fixes https://github.com/jitsi/jitsi-videobridge/pull/1506
> Properly prioritize screen share low bandwidth mode

- pom.xml
Also, don't truncate the source list in VideoParser logs.
> Update jmt: Fix DtlsStack threading deadlock; add timeout for DTLS handshakes.

- jvb/src/main/kotlin/org/jitsi/videobridge/Main.kt
- pom.xml
This allows access to the REST API via an SSH tunnel without CORS issues.
> allow cors on the private httpserver

- jvb/src/main/java/org/jitsi/videobridge/AbstractEndpoint.java
- jvb/src/main/java/org/jitsi/videobridge/Endpoint.java
- jvb/src/main/java/org/jitsi/videobridge/rest/root/debug/Debug.java
- jvb/src/main/kotlin/org/jitsi/videobridge/octo/OctoEndpoint.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/octo/config/OctoRtpReceiver.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/octo/config/OctoRtpSender.kt
- jvb/src/test/java/org/jitsi/videobridge/rest/root/debug/DebugTest.java
- pom.xml
Depends on https://github.com/jitsi/jitsi-media-transform/pull/325
> Allow querying the state of endpoint debug features

- jvb/src/main/java/org/jitsi/videobridge/Endpoint.java
- jvb/src/main/kotlin/org/jitsi/videobridge/EndpointK.kt
Continuation of the work started in https://github.com/jitsi/jitsi-videobridge/pull/1593
> Refactor endpoint to Kotlin part 2

- jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/Prioritize.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/VideoConstraints.kt
Prioritize#getEffectiveConstraints creates lots of these for endpoints outside lastN, so let's save some GC.
> Create and use a singleton VideoConstraints.NOTHING object.

- pom.xml
> Fix: Avoid spinning in DTLS handshake.

- jvb/src/main/kotlin/org/jitsi/videobridge/Endpoint.kt
This prevents SCTP DataChannel messages from being processed out of order, causing warnings on channel initialization and potential issues with Last-N selection.
I originally proposed fixing this with a different implementation in #1309. A simpler solution (reusing `PacketInfoQueue`) was then proposed by @mstyura in #1318.
Neither of the original PRs are in a mergeable state now `Endpoint` is re-implemented in Kotlin.
This change takes the approach from #1318, and applies it to the new Kotlin state of affairs.
> Process data channel messages sequentially

- jvb/src/main/java/org/jitsi/videobridge/stats/VideobridgeStatistics.java
- pom.xml
depends on https://github.com/jitsi/jitsi-media-transform/pull/353
> feat: Implements tracking of the aimd bwe expirations.

- jvb/src/main/kotlin/org/jitsi/videobridge/AbstractEndpointMessageTransport.kt
> Change "SEND" to "SENT" in EndpointMessageTransport.

- jvb/src/main/java/org/jitsi/videobridge/xmpp/MediaSourceFactory.java
- jvb/src/test/java/org/jitsi/videobridge/xmpp/MediaSourceFactoryTest.java
- pom.xml
Depends on https://github.com/jitsi/jitsi-media-transform/pull/374
> feat: add source name to MediaSourceDesc

- .github/workflows/maven.yml
- jvb-api/jvb-api-client/pom.xml
- jvb-api/jvb-api-client/src/test/kotlin/org/jitsi/videobridge/api/util/WebSocketClientTest.kt
- jvb-api/pom.xml
- jvb/pom.xml
- jvb/src/main/java/org/jitsi/videobridge/Videobridge.java
- jvb/src/main/java/org/jitsi/videobridge/rest/JSONDeserializer.java
- jvb/src/main/java/org/jitsi/videobridge/rest/JSONSerializer.java
- jvb/src/main/java/org/jitsi/videobridge/stats/Statistics.java
- jvb/src/main/java/org/jitsi/videobridge/stats/VideobridgeStatistics.java
- jvb/src/main/kotlin/org/jitsi/videobridge/transport/dtls/DtlsTransport.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/transport/ice/IceTransport.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/xmpp/XmppConnection.kt
- jvb/src/test/kotlin/org/jitsi/videobridge/cc/allocation/BitrateControllerPerfTest.kt
- pom.xml
This depends on:
- jitsi/jitsi-xmpp-extensions#55
- jitsi/jicoco#157
> Update dependencies, cleanup deprecations

- jvb/src/main/java/org/jitsi/videobridge/EndpointMessageTransport.java
- jvb/src/main/java/org/jitsi/videobridge/cc/allocation/BandwidthAllocator.java
- jvb/src/main/java/org/jitsi/videobridge/octo/ConfOctoTransport.java
- jvb/src/main/java/org/jitsi/videobridge/octo/OctoEndpointMessageTransport.java
- jvb/src/main/java/org/jitsi/videobridge/shim/ChannelShim.java
- jvb/src/main/java/org/jitsi/videobridge/xmpp/MediaSourceFactory.java
- jvb/src/main/kotlin/org/jitsi/videobridge/Endpoint.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/MultiStreamConfig.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/AllocationSettings.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/BandwidthAllocation.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/BitrateController.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/message/BridgeChannelMessage.kt
- jvb/src/test/kotlin/org/jitsi/videobridge/MediaSourceFactoryTest.kt
- jvb/src/test/kotlin/org/jitsi/videobridge/cc/allocation/BitrateControllerNewTest.kt
- jvb/src/test/kotlin/org/jitsi/videobridge/cc/allocation/BitrateControllerPerfTest.kt
- jvb/src/test/kotlin/org/jitsi/videobridge/cc/allocation/BitrateControllerTest.kt
- jvb/src/test/kotlin/org/jitsi/videobridge/message/BridgeChannelMessageTest.kt
The next step after https://github.com/jitsi/jitsi-videobridge/pull/1780
> Feat: source name based forwarded sources

- jvb/src/main/java/org/jitsi/videobridge/cc/vp8/VP8AdaptiveSourceProjectionContext.java
- jvb/src/main/java/org/jitsi/videobridge/cc/vp8/VP8FrameProjection.java
- jvb/src/main/java/org/jitsi/videobridge/cc/vp8/VP8QualityFilter.java
- jvb/src/main/kotlin/org/jitsi/videobridge/Endpoint.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/cc/vp9/Vp9AdaptiveSourceProjectionContext.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/cc/vp9/Vp9FrameProjection.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/cc/vp9/Vp9QualityFilter.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/relay/Relay.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/transport/octo/BridgeOctoTransport.kt
- jvb/src/test/java/org/jitsi/videobridge/cc/vp8/VP8AdaptiveSourceProjectionTest.java
- jvb/src/test/kotlin/org/jitsi/videobridge/cc/vp9/Vp9AdaptiveSourceProjectionTest.kt
- jvb/src/test/kotlin/org/jitsi/videobridge/cc/vp9/Vp9QualityFilterTest.kt
- pom.xml
Depends on https://github.com/jitsi/jitsi-rtp/pull/99 and https://github.com/jitsi/jitsi-media-transform/pull/391.
> Convert PacketInfo.receivedTime to instant, and adjust users.

- jvb/src/main/java/org/jitsi/videobridge/EndpointMessageTransport.java
- jvb/src/main/java/org/jitsi/videobridge/Videobridge.java
- jvb/src/main/java/org/jitsi/videobridge/stats/VideobridgeStatistics.java
- jvb/src/main/kotlin/org/jitsi/videobridge/EndpointMessageTransportConfig.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/Main.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/VersionConfig.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/relay/RelayMessageTransport.kt
- jvb/src/main/resources/reference.conf
- jvb/src/test/kotlin/org/jitsi/videobridge/VideobridgeTest.kt
- pom.xml
Sending dummy value for release ID for now.
> Send release ID in bridge statistics.

- jvb/src/main/kotlin/org/jitsi/videobridge/relay/RelayMessageTransport.kt
When this.webSocket is initialized in doConnect(), webSocketConnected
detects this as an existing web socket, closes it and re-connects. I
think the only reason this doesn't keep happening continually is that
the second time webSocket.session is null.
Reported by @paweldomas
> fix: Closing the relay WS immediately upon initial connection.

- jvb/src/main/kotlin/org/jitsi/videobridge/relay/RelayMessageTransport.kt
Fix a problem with a Relay.expire() call blocking the colibri queue thread. Reported by @paweldomas.
> Run WebSocketClient.stop in an IO thread.

- jvb/src/main/java/org/jitsi/videobridge/rest/JSONDeserializer.java
- jvb/src/main/java/org/jitsi/videobridge/rest/JSONSerializer.java
2. Use IceCandidatePacketExtension instead of CandidatePacketExtension.
> 1. Use String for id in RtpHeaderExtension.

- doc/allocation.md
- doc/constraints.md
- jvb/src/main/java/org/jitsi/videobridge/EndpointMessageTransport.java
- jvb/src/main/kotlin/org/jitsi/videobridge/Endpoint.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/AllocationSettings.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/BitrateController.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/message/BridgeChannelMessage.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/relay/RelayMessageTransport.kt
- jvb/src/main/resources/reference.conf
- jvb/src/test/java/org/jitsi/videobridge/xmpp/MediaSourceFactoryTest.java
- jvb/src/test/kotlin/org/jitsi/videobridge/cc/allocation/AllocationSettingsTest.kt
- jvb/src/test/kotlin/org/jitsi/videobridge/cc/allocation/BitrateControllerNewTest.kt
- jvb/src/test/kotlin/org/jitsi/videobridge/cc/allocation/BitrateControllerPerfTest.kt
- jvb/src/test/kotlin/org/jitsi/videobridge/cc/allocation/BitrateControllerTest.kt
- jvb/src/test/kotlin/org/jitsi/videobridge/message/BridgeChannelMessageTest.kt
Removes legacy constraints format.
Enables multi stream mode with backwards compatibility flow by default.
> Ref: multi stream by default, remove legacy constraints

- jvb/src/main/java/org/jitsi/videobridge/Conference.java
- jvb/src/main/java/org/jitsi/videobridge/Videobridge.java
- jvb/src/main/java/org/jitsi/videobridge/stats/VideobridgeStatistics.java
* ref: Port totalConferencesCompleted stat to Metric.
* ref: Rename totalConferencesCreated variable and metric.
> Port totalConferencesCompleted stat to Metric.

- jvb/src/main/java/org/jitsi/videobridge/Conference.java
- jvb/src/main/java/org/jitsi/videobridge/Videobridge.java
- jvb/src/main/java/org/jitsi/videobridge/stats/VideobridgeStatistics.java
- jvb/src/main/kotlin/org/jitsi/videobridge/transport/ice/IceTransport.kt
- jvb/src/test/kotlin/org/jitsi/videobridge/cc/allocation/BitrateControllerTraceTest.kt
Also fixes a test failure in BitrateControllerTraceTest and removes a trailing comma ktlint wasn't happy about.
> ref: Port ICE stats to Metrics.

- pom.xml
Fix dominant speaker identification with silence and a single endpoint sending audio.
> chore: Update jitsi-utils

- jvb/src/main/kotlin/org/jitsi/videobridge/Endpoint.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/SsrcCache.kt
May be useful for tuning the limits.
> Add some stats for SSRC rewriting.

- jvb/src/main/java/org/jitsi/videobridge/util/UlimitCheck.java
Also adjust limits under which a warning is logged.
> fix: Treat "unlimited" correctly (fixes #1971).

- jitsi-media-transform/pom.xml
- jitsi-media-transform/spotbugs-exclude.xml
- jitsi-media-transform/src/test/kotlin/org/jitsi/nlj/KotestProjectConfig.kt
- jvb/pom.xml
- jvb/src/test/kotlin/org/jitsi/videobridge/VideobridgeTest.kt
- pom.xml
- rtp/spotbugs-exclude.xml
- rtp/src/test/kotlin/org/jitsi/test_helpers/matchers/RtpPacket.kt
(Including jicoco dependency.)
> Update to Jetty 11.0.14.

- jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/stats/EndpointConnectionStats.kt
or suspiciously high, or the sender's "delay since last SR" values is
too high.
> fix: Do not update RTT when the calculated value is invalid

- jvb/src/main/java/org/jitsi/videobridge/xmpp/MediaSourceFactory.java
- pom.xml
> Update jitsi-xmpp-extensions and jitsi-utils.

- debian/control
Reverts 499c312 and adds java17.
> feat: Updates java dependencies to include java17.

- jvb/src/main/kotlin/org/jitsi/videobridge/Endpoint.kt
- resources/analyze-timeline2.pl
- **feat: Add a timeline event when the packet was sent over ICE.**
- **feat: Add another analize-timeline script.**
> feat: Add a timeline event when the packet was sent over ICE.

- jvb/src/main/kotlin/org/jitsi/videobridge/relay/RelayedEndpoint.kt
Rather than processing them synchronously in the I/O thread.
> Fix: Push packets received from ICE onto a queue.

- jvb/resources/jvb.sh
- pom.xml
(The flag is no longer needed with this change.)
> Bump ice4j to use SocketPool.  Remove usePlainDatagramSocketImpl flag.

- jvb/src/main/java/org/jitsi/videobridge/xmpp/MediaSourceFactory.java
- jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/AllocationSettings.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/BandwidthAllocation.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/BandwidthAllocator.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/BitrateController.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/SingleSourceAllocation.kt
- jvb/src/main/kotlin/org/jitsi/videobridge/cc/config/BitrateControllerConfig.kt
- jvb/src/main/resources/reference.conf
- jvb/src/test/kotlin/org/jitsi/videobridge/cc/allocation/BitrateControllerTest.kt
- jvb/src/test/kotlin/org/jitsi/videobridge/cc/allocation/EffectiveConstraintsTest.kt
- **fix: Improve logging.**
- **ref: Remove unused code.**
- **ref: Remove unnecessary functions.**
- **ref: Remove unused config option.**
- **ref: Remove unused code.**
- **ref: Single line comments.**
> Minor cleanup, removing unused code

- pom.xml
* fix: Fail early if IMDS returns an error. (jitsi/ice4j#298)
* Add IMDSv2 support to AwsCandidateHarvester and replace URLConnectionn with HttpRequest (jitsi/ice4j#297)
* Add Java 21 to GitHub testing matrix (jitsi/ice4j#296)
> chore: Update ice4j
