src/org/jitsi/videobridge/rest/JSONDeserializer.java
src/org/jitsi/videobridge/rest/JSONSerializer.java

REST api is missing a few features compared to the xmpp api, not sure if there's a bigger update in the works but I added support for header extensions here.

add handling in the rest api for header extensions field

---

resources/collect-dump-logs.sh
resources/install/debian/init.d
resources/install/linux-64/jvb.sh
resources/install/linux/jvb.sh
resources/install/macosx/jvb.sh

When launching Java from a wrapper script, it's usually better to use
exec, so that the extra bash process isn't hanging around. It also helps
shutdown and process monitoring (like with upstart, systemd, docker,
etc.) since they would be monitoring (and killing) the Java process
itself, instead of the wrapper script.

Use exec in wrapper scripts for launching java

---

src/main/java/org/jitsi/videobridge/Content.java
src/main/java/org/jitsi/videobridge/RtpChannel.java

Does not really fix anything, as the SSRC is converted to unsigned before being sent out (in SourcePacketExtension.setSSRC). However, this eases debugging and makes the code cleaner IMHO.
The same problem seems to exist in libjitsi:SSRCFactoryImpl.doGenerateSSRC, though.

Always generate a positive SSRC.

---

src/main/java/org/jitsi/videobridge/simulcast/SimulcastEngine.java
src/main/java/org/jitsi/videobridge/simulcast/sendmodes/RewritingSendMode.java

SimulcastEngine defines an internal Tracked class which is being used superfluously. I've deleted the class and replaced its use with a (boolean) method return value.
Additionally, I've fixed a few simple IntelliJ IDEA warnings (in a separate commit), one of which is a source code simplification.

Delete superfluous Tracked class

---

resources/collect-dump-logs.sh

This is a safer version of the collect dumps scripts, which properly handles more than one memory dump, and correctly checks for a running java process before choosing whether to dump the live process or look for OOM dumps.

safer version of the the collect scripts

---

src/main/java/org/jitsi/videobridge/RtpChannel.java

This fixes a nasty race condition during media channel establishment. We noticed it in mixer mode using an automated test with all components on a single machine, so it might be due to very tight timing.
In RtpChannel, during the execution of 
stream.start()
a media packet from the peer comes in already, indirectly triggering 
stream.setDirection(MediaDirection.SENDRECV);
in another thread.
However, as MediaStreamImpl.started is not yet set to true, this call effectively does not start the outgoing stream, resulting in a one-way media stream.
This could alternatively be fixed by declaring MediaStreamImpl.start/stop/setDirection as "synchronized" in libjitsi.

Synchronize access to RtpChannel.stream.

---

src/main/java/org/jitsi/videobridge/RawUdpTransportManager.java
src/test/java/org/jitsi/videobridge/RawUdpConferenceTest.java
src/test/java/org/jitsi/videobridge/VideoBridgeTestSuite.java

The code is mostly taken from here, which should also be Apache-licensed
https://issues.apache.org/jira/browse/JCS-40
It fixes the second problem in https://github.com/jitsi/jitsi-videobridge/issues/102
It might be desirable anyway to allow to configure "the" IP address. Suggestions for a property name?

Use getLocalHostLanAddress to avoid using 127.0.0.1 as the local IP

---

src/main/java/org/jitsi/videobridge/Content.java
src/main/java/org/jitsi/videobridge/RtpChannel.java
src/main/java/org/jitsi/videobridge/VideoChannel.java
src/main/java/org/jitsi/videobridge/Videobridge.java
src/main/java/org/jitsi/videobridge/health/Health.java
src/test/java/org/jitsi/videobridge/RawUdpConferenceTest.java

(This PR includes https://github.com/jitsi/jitsi-videobridge/pull/128 in terms of test infrastructure, please accept that one before).
This fixes the first part of https://github.com/jitsi/jitsi-videobridge/issues/102 and presumably also https://github.com/jitsi/jitsi-videobridge/issues/9
The problem was:
RtpChannel.initialize calls transportConnected because for RawUdpTransportManager, isConnected is immediately true. Then transportConnected -> maybeStartStream -> getRTPLevelRelayType
As the RTP level type is not yet set at this point in time, it will be set to the default TRANSLATOR in getRTPLevelRelayType.
There is explicitly a comment stating
/*
* We've postponed the invocation of the method
* getRTPLevelRelayType() in order to make sure that the conference
* focus has had a chance to …

Fix setting RTP relay type to mixer

---

pom.xml
src/main/java/org/jitsi/videobridge/Videobridge.java
src/main/java/org/jitsi/videobridge/xmpp/ComponentImpl.java
src/test/java/org/jitsi/videobridge/FocusControlTest.java

This adds health-check's namespace to the feature list of JVB XMPP component. Fixes TODO for "jabber:iq:version" namespace.

Adds health checks to XMPP component's feature list.

---

src/main/java/org/jitsi/videobridge/VideoChannel.java

The main for loop at line 894 short circuits if a source group does not
have a simulcast semantic. If there are no simulcast source groups at
all, the ssrc2stream hash map is never populated, triggering a NPE
after the main for loop.
This change detects that there were no simulcast groups and skips
running those final steps.

Prevent NullPointerException when there are no simulcast source groups.

---

resources/install/debian/init.d

Fixes stop of init script to work even if process is missing, otherwise it even fails to uninstall.

Fixes stop of init script to work on missing process.

---

src/main/java/org/jitsi/videobridge/IceUdpTransportManager.java

Fixes a NullPointerException in IceUdpTransportManager which occurs repeatedly and regularly. That's likely happening during health checks (from Jicofo, for example). No functionality appears to be broken.

Fix a NullPointerException in IceUdpTransportManager

---

src/main/java/org/jitsi/videobridge/Endpoint.java
src/main/java/org/jitsi/videobridge/health/Health.java

checks. Does not add SctpConnection-s to the audio and video contents.

Uses a separate "data" content in the conference created for health

---

pom.xml
src/main/java/org/jitsi/videobridge/SctpConnection.java
src/main/java/org/jitsi/videobridge/VideoChannel.java

ensure that the calling thread does not block. We have
observed that blocking this thread (e.g. by having it eventually try
to write to a Socket) results in calls to usrsctp_socket to block (i.e.
to our inability to initialize any new SCTP sockets).

Uses a PacketQueue for packets coming out of the SCTP stack in order to

---

src/main/java/org/jitsi/videobridge/RtpChannel.java

Tries to solve a problem reported by Somil Bansal on the dev mailing list. Calls setTarget() before setConnector(), because the latter starts the DTLS server or client, which shouldn't be started without a target. See a discussion here: http://lists.jitsi.org/pipermail/dev/2016-March/027119.html

Calls MediaStream#setTarget() before setConnector().

---

pom.xml
src/main/java/org/jitsi/videobridge/IceUdpTransportManager.java
src/main/java/org/jitsi/videobridge/RawUdpTransportManager.java
src/main/java/org/jitsi/videobridge/RtpChannel.java
src/main/java/org/jitsi/videobridge/SctpConnection.java
src/main/java/org/jitsi/videobridge/TransportManager.java
src/main/java/org/jitsi/videobridge/influxdb/LoggingHandler.java

Reports the value of setup attribute defined by https://tools.ietf.org/html/rfc4145#section-4 (that libjitsi's DTLS supports already) from Videobridge to the API client allocating the channel. Takes into account the value sent by the API client to Videobridge. Requires https://github.com/jitsi/libjitsi/pull/119 and https://github.com/jitsi/ice4j/pull/56.
The following modifications were applied while trying to remove a 1 second hard minimum on connectivity establishment between Videobridge and Chrome/WebRTC. Related modifications in lib-jitsi-meet (i.e. which will be introduced in a branch there with the same name) (will) depend on these.

Support RFC 4145 setup attribute

---

src/main/java/org/jitsi/videobridge/simulcast/SimulcastSender.java
src/main/java/org/jitsi/videobridge/simulcast/SimulcastSenderManager.java

Triggers a change in the received stream when the targetOrder changes as
a result of a change of the overrideOrder.

Allows adaptive-simulcast to disable the HD layer immediately.

---

pom.xml

Imports https://github.com/jitsi/jitsi-videobridge/pull/123 from @champtar's fork into a jitsi/jitsi-videobridge branch in order to enable automatic testing of further changes.

Update bcprov-jdk15on to 1.54

---

src/main/java/org/jitsi/videobridge/ratecontrol/AdaptiveSimulcastBitrateController.java

Adds null checks which could occur if adaptive simulcast is enabled, but
simulcast is disabled.

Enable adaptive simulcast by default

---

pom.xml
src/main/java/org/jitsi/videobridge/RtpChannel.java
src/main/java/org/jitsi/videobridge/transform/RtxTransformer.java

Fixes numerous small issues with the RTX format. Strips RTX from incoming RTX packets, in order to work with simulcast and its SSRC rewriting. Passes RTX configuration to libjitsi's RetransmissionRequester.
Note: this depends on libjitsi#129.

Fixes and improvements for RTX.

---

src/main/java/org/jitsi/videobridge/EventFactory.java

(use ```Dictionary<String, Object>``` for Event properties)
Signed-off-by: Etienne CHAMPETIER <champetier.etienne@gmail.com>

Remove some compiler warnings

---

src/main/java/org/jitsi/videobridge/pubsub/PubSubPublisher.java
src/main/java/org/jitsi/videobridge/simulcast/sendmodes/RewritingSendMode.java

if the key doesn't exist Map<>.get return null,
and we are not putting null as value, so use that.

Don't use Map<>.containsKey before Map<>.get

---

src/main/java/org/jitsi/videobridge/RawUdpTransportManager.java

Use NAT_HARVESTER_PUBLIC_ADDRESS to configure raw udp transport bind address.
This is useful if there are multiple IP addresses in the machine, and getLocalHostLanAddress() could get the wrong IP, or JVB is running behind a NAT.
NOTE: both public and local addresses need to be configured.

Configure the raw udp transport bind address.

---

src/main/java/org/jitsi/videobridge/Endpoint.java
src/main/java/org/jitsi/videobridge/simulcast/SimulcastSender.java
src/main/java/org/jitsi/videobridge/simulcast/SimulcastSenderManager.java

When data channel connection establishment is fast and if the selected
endpoint data channel message is sent early enough then when one user
(re)joins a call, it's getting a good quality stream from the participant
that was already in the room. But the user that was already in the room,
gets a low quality stream from the newly joined client. So effectively,
in a 1:1 session, one user always ends up with a low quality stream of
the remote... The user that joined first.

Fixes a problem where you may get stuck with low quality video

---

src/main/java/org/jitsi/videobridge/IceUdpTransportManager.java
src/main/java/org/jitsi/videobridge/Videobridge.java

TcpHarvester binds to specific local addresses, Jetty binds to all/any
local addresses. Consequently, Jetty will fail to bind if TcpHarvester
binds first and Jetty is supposed to share a port with TcpHarvester. To
resolve this failure, initialize TcpHarvester as late as possible and
leave Jetty to bind at startup.

Revert 5c577d2

---

src/main/java/org/jitsi/videobridge/RtpChannel.java

After #190 when RawUdpTransport is used the media stream never starts, because with RawUdpTransport the streamTarget is always null by definition, and so maybeStartStream() returns too early without reaching stream.start().
I mantained the setTarget / setConnector order as in #190.

Fix a regression after #190 when RawUdpTransport is used.

---

pom.xml
src/main/java/org/jitsi/videobridge/RtpChannel.java
src/main/java/org/jitsi/videobridge/VideoChannel.java
src/main/java/org/jitsi/videobridge/Videobridge.java
src/main/java/org/jitsi/videobridge/transform/RtpChannelTransformEngine.java

Adds packet delay property to the RTP channels which is
meant to be used during automated testing of the lip-sync
feature.

Implement packet delay in RtpChannel

---

src/main/java/org/jitsi/videobridge/simulcast/SimulcastReceiver.java
src/main/java/org/jitsi/videobridge/simulcast/sendmodes/RewritingSendMode.java

Adds a warning message in an effort to identify the cause of failing stream switching in the context of simulcast.

Failing stream switching warnings.

---

pom.xml
src/main/java/org/jitsi/videobridge/Conference.java
src/main/java/org/jitsi/videobridge/Videobridge.java
src/main/java/org/jitsi/videobridge/eventadmin/callstats/Activator.java
src/main/java/org/jitsi/videobridge/eventadmin/callstats/CallStatsConferenceStatsHandler.java
src/main/java/org/jitsi/videobridge/health/Health.java

Callstats uses conference name to report. Pulls callstats from maven central.

callstats uses conference name to report

---

src/main/java/org/jitsi/videobridge/stats/CallStatsIOTransport.java

Skips registering an osgi service on every callstats initializing, as it is re-authenticating every few hours and firing onInitialized.

Skips registering an osgi service on every callstats initializing

---

resources/collect-dump-logs.sh

We want to make sure we grab the java heap dump, even if the process
appears to be running.  If the JVB has crashed (with OOM, for example),
the JVM might be configured to take a heap dump. During that time, the
process will appear running, but the JVM won't allow us to connect to it
and take a heap/thread dump.

Updates the collect-dump-logs.sh

---

src/main/java/org/jitsi/videobridge/RawUdpTransportManager.java

Basically this is a fix to my previous fix: if JVB is NATed, the RawUdpTransport cannot bind to the public address so use the harvester local address instead.
With this change we can use NATed JVB and RawUdpTransport.

Use harvester local address to configure RawUdpTransport bind address.

---

src/main/java/org/jitsi/videobridge/eventadmin/callstats/CallStatsConferenceStatsHandler.java

Makes the CallStatsConferenceStatsHandler.statisticsExecutor static. We
have run into a situation where we create many executors that storm the
callstats object, resulting in an OOM. Making this static should prevent
this from happening in the future, if we mess this up again.

Makes an executor static.

---

src/main/java/org/jitsi/videobridge/VideoChannel.java

The change includes sequence number rewriting on the video channel. If an rtp packet is getting forwarded, we update the sequence number. otherwise, we keep track of the delta since the last transmitted sequence number.
We also take care of seq. no. and delta wrap arounds

[video channel] sequence number rewriting for video rtp packets

---

resources/mvn-exec.sh

It turns out that the mvn exec script is not POSIX compliant and it
requires features from bash. Also, a basename should be a dirname.

Fixes the mvn-exec.sh script.

---

src/main/java/org/jitsi/videobridge/Conference.java
src/main/java/org/jitsi/videobridge/ConferenceSpeechActivity.java
src/main/java/org/jitsi/videobridge/Endpoint.java
src/main/java/org/jitsi/videobridge/eventadmin/influxdb/LoggingHandler.java

Both Conference and Endpoint have "expired" properties which can be used to determine if instances are valid, so using WeakReference only adds extra complexity.
I need these changes for another work which will require to store expired Endpoint instances until Conference is not expired and it may break logic which depends on WeakReferences<Endpoint>.

Do not use WeakReference on Endpoint and Conference

---

src/main/java/org/jitsi/videobridge/RtpChannel.java

Add the mapping from SSRC to EndpointID to the Synchronizer instance used by
RecorderRtpImpl when new SSRCs are signalled over colibri.

Fix #227: Fix SSRC Mapping when people join a recorded conversation

---

src/main/java/org/jitsi/videobridge/Channel.java
src/main/java/org/jitsi/videobridge/RtpChannel.java
src/main/java/org/jitsi/videobridge/SctpConnection.java
src/main/java/org/jitsi/videobridge/VideoChannel.java

Only expires channels once. Fixes the values reported in statistics.

fix: Fixes a bug reported by @aaronkvanmeerten

---

src/main/java/org/jitsi/videobridge/eventadmin/callstats/CallStatsConferenceStatsHandler.java

Fixes possible memory leak, where conference references from ConferencePeriodicProcessible are left in statisticsExecutor if conferenceExpired preceded the call to CallStatsStartConferenceListener.onResponse.

Fix leaking conferences from callstats handler

---

src/main/java/org/jitsi/videobridge/RtpChannel.java
src/main/java/org/jitsi/videobridge/VideoChannel.java

Sends keyframe requests preemptively when an endpoint becomes the dominant speaker, in anticipation of receivers selecting that endpoint.

Stream switching

---

src/main/java/org/jitsi/videobridge/Channel.java
src/main/java/org/jitsi/videobridge/Conference.java
src/main/java/org/jitsi/videobridge/EndpointConnectionStatus.java
src/main/java/org/jitsi/videobridge/EventFactory.java
src/main/java/org/jitsi/videobridge/osgi/JvbBundleConfig.java

This PR adds endpoint connection status monitoring which sends notifications over data channels when connectivity status changes. Endpoint connection status is considered inactive when there is no media or ICE related traffic on any of it's channels. This is tracked in new 'lastTransportActivityTime' timestamp added to every Channel. It is updated whenever RTP/RTCP packet is received or when ICE "consent freshness" check succeeds(which is now sent more often - every 3 seconds).

Endpoint connection monitoring

---

src/main/java/org/jitsi/videobridge/IceUdpTransportManager.java

fix(logging): Don't try to get the transport type for conferences

---

src/main/java/org/jitsi/videobridge/simulcast/SimulcastReceiver.java

https://github.com/jitsi/jitsi-videobridge/commit/245ed9d3342e65c67cd3e9659c9c344760ca7713 introduces an NPE under certain occasions. This commit fixes it.

Fix for NPE in simulcast receiver.

---

openfire/src/java/org/jitsi/videobridge/openfire/JvbOpenfireBundleConfig.java
openfire/src/java/org/jitsi/videobridge/openfire/PluginImpl.java
openfire/src/java/org/jitsi/videobridge/openfire/SLF4JBridgeHandlerBundleActivator.java
pom.xml

This is a follow-up to #328.
It adds:
- silent ignores of non-root files in the native libraries (which were ignored too, before my earlier changes)
- logging being forced through the Openfire-provided logging framework (instead of std-out). Fixes #329 
- compliance with Jitsi coding conventions.

Openfire plugin issues

---

src/main/java/org/jitsi/videobridge/simulcast/SimulcastSender.java
src/main/java/org/jitsi/videobridge/simulcast/sendmodes/SendMode.java

When we don’t have a remote clock for the higher layer stream, we avoid upscaling in order to avoid breaking timestamp rewriting. This PR implements a retry logic that attempts to upscale if the the upscale was unsuccessful.

fix(sim): Retries to scale-up, if we failed to send the target order.

---

.gitignore

Intellij tends to create project files in subdirectories (notably for the Openfire plugin, that is nested in this project. Those files should also be ignored by Git.

Git should ignore nested Intellij IDEA project files.

---

src/main/java/org/jitsi/videobridge/eventadmin/metrics/MetricLoggingHandler.java

This is a fix for https://github.com/jitsi/jitsi-videobridge/issues/345
The code uses U+2028 on two lines, where the other lines use regular LF's. The U+2028 has reported to cause problems on the development environment of some: https://github.com/jitsi/jitsi-videobridge/issues/178#issuecomment-255527321
Replaced U+2028 with regular LF.

Should not use non-standard newline character.

---

src/main/java/org/jitsi/videobridge/xmpp/ComponentImpl.java

This is a fix for https://github.com/jitsi/jitsi-videobridge/issues/335
The Component implementation that wraps the Videobridge instance should expose that Videobridge instance publicly, instead of privately.
Obtaining the Videobridge instance can be achieved with other data that is publicly exposed by the component (notably getBundleContext() and ServiceUtils2.getService), and the implementation already contains a private method that exposes the instance. This method can be made publicly accessible, which would remove the need to duplicate its implementation.

Component should expose its videobridge instance

---

src/main/java/org/jitsi/videobridge/xmpp/ComponentImpl.java

The superclass, ComponentBase, is an implementation of an *external*, not internal, component.

Javadoc fix.

---

openfire/src/java/org/jitsi/videobridge/openfire/PluginImpl.java

This is a fix for https://github.com/jitsi/jitsi-videobridge/issues/338 which is an issue similar to https://github.com/jitsi/jitsi-videobridge/issues/335.
When the Openfire plugin exposes its ComponentImpl instance, it's data can, for instance, be used to populate admin console pages (listings of active conferences, etc).

Openfire plugin should expose its Component

---

src/main/java/org/jitsi/videobridge/HarvesterConfiguration.java
src/main/java/org/jitsi/videobridge/Videobridge.java

This is a fix for https://github.com/jitsi/jitsi-videobridge/issues/347
When using a constant to refer to a property, this is typically done to avoid typos and add configuration. Keeping such constants non-public is counterproductive, as it forces people to revert to manually typing the property name (and typically hides javadoc).
Constants that are used to store property names should be publicly accessible.

Property name constants should be publicly accessible.

---

openfire/src/java/org/jitsi/videobridge/openfire/PluginImpl.java
src/main/java/org/jitsi/videobridge/Content.java
src/main/java/org/jitsi/videobridge/IceUdpTransportManager.java
src/main/java/org/jitsi/videobridge/RtpChannel.java
src/main/java/org/jitsi/videobridge/ratecontrol/LastNBitrateController.java
src/main/java/org/jitsi/videobridge/rest/JSONDeserializer.java
src/main/java/org/jitsi/videobridge/stats/PubSubStatsTransport.java

This is a fix for https://github.com/jitsi/jitsi-videobridge/issues/342
When an exception occurs, it should not be ignored completely. If handling is not needed, the exception should be logged (if only at the lowest of log levels). This greatly reduces confusion while debugging a situation where a bug occurs caused by an exception that the original developer believed was "impossible".

Exceptions should not be completely ignored

---

pom.xml
src/main/java/org/jitsi/videobridge/xmpp/ComponentImpl.java

Updates Jicoco in order to use single thread packet processor. DO NOT MERGE(Jicoco is referenced by the SNAPSHOT version)

Process XMPP packets in order

---

pom.xml
src/main/java/org/jitsi/videobridge/xmpp/ComponentImpl.java

Updates Jicoco in order to measure packets processing time in the XMPP component.

Measure XMPP packet processing time

---

doc/http.md
src/main/java/org/jitsi/videobridge/rest/HandlerImpl.java
src/main/java/org/jitsi/videobridge/rest/RESTBundleActivator.java

This PR adds a new config (`org.jitsi.videobridge.ENABLE_REST_COLIBRI`) to turn on/off the `/colibri/*` REST API endpoints.
The default value for this Config is `true`, therefore the current behavior is maintained.
When setting `org.jitsi.videobridge.ENABLE_REST_COLIBRI` to `false`, it is possible to have the JVB to serve HTTP content without exposing the Colibri REST API endpoints.

Config to turn on/off /colibri/* REST API endpoints

---

doc/callstats.md
src/main/java/org/jitsi/videobridge/stats/CallStatsIOTransport.java

Support both shared secret and public/private keys. 
If both are set, prefer shared secret (callstats.io default).

Update callstats.io authentication to support shared secret and public/private keys

---

src/main/java/org/jitsi/videobridge/Channel.java
src/main/java/org/jitsi/videobridge/SctpConnection.java

Avoids obtaining two locks in Content#createSctpConnection.

Reduce synchronization

---

src/main/java/org/jitsi/videobridge/Conference.java

Clients were not receiving updates to the last-n endpoints when the
active speaker changed. Now, the LastNController for each
VideoChannel should be notified as active speaker updates and will
push out last-n change events, if necessary.

Fix: Update last-n on dominant speaker change

---

src/main/java/org/jitsi/videobridge/Conference.java
src/main/java/org/jitsi/videobridge/EndpointConnectionStatus.java
src/main/java/org/jitsi/videobridge/SctpConnection.java
src/main/java/org/jitsi/videobridge/VideoChannel.java

More details about the message and Endpoint will be logged when SCTP transfer fails. Also SCTP stack events will be logged.

Provide more info when the data channel transfer fails

---

src/main/java/org/jitsi/videobridge/Conference.java

Summary:
Conferences have a default lastActivityTime of zero.
It could be possible for VideobridgeExpireThread
to run immediately after a conference is created,
thereby expiring the conference.

Set a default lastActivityTime on Conference creation

---

pom.xml
src/main/java/org/jitsi/videobridge/BitrateController.java

The VP8 FIR fixes are in LJ. This PR fixes an issue with the bitrate allocation algorithm where the optimal quality for endpoints outside the lastN set should be -1.

VP8 FIR and bitrate allocation fixes

---

doc/single-port.md

Points to ice4j for documentation of existing properties.

doc: Updates the single port documentation.

---

pom.xml
src/main/java/org/jitsi/videobridge/RtpChannel.java
src/main/java/org/jitsi/videobridge/VideoChannel.java
src/main/java/org/jitsi/videobridge/cc/BandwidthProbing.java
src/main/java/org/jitsi/videobridge/cc/BitrateController.java
src/main/java/org/jitsi/videobridge/cc/SimulcastController.java

This PR contains fixes and features related to adaptivity (bandwidth estimations, bandwidth probing, simulcast). This PR depends on https://github.com/jitsi/libjitsi/pull/297
1. Various fixes in the padding budget calculation:
a. We don't take into account expired endpoints
b. we're more careful as to what we consider inactive, and this affects the padding calculation.
2. Simulcast related fixes, specifically about requesting key frames:
a. when we detect that a stream has been suspended, we only ask for a key frame if the suspended stream is forwarded
b. when temporal filtering is enabled we carelessly where requesting keyframes on temporal layer changes
3. makes a bunch of stuff configurable through java sys properties.

Bandwidth estimation and probing for bandwidth fixes

---

doc/rest.md
src/main/java/org/jitsi/videobridge/rest/PublicRESTBundleActivator.java
src/main/java/org/jitsi/videobridge/rest/RESTBundleActivator.java

Renames the properties used to configure the REST interfaces.
Makes the properties prefixed with "org.jitsi.videobridge.rest" control the public instead of the private interface. Uses the prefix "org.jitsi.videobridge.rest.private" for the private interface. Does not use the "org.jitsi.videobridge.rest.public" prefix.
The new defaults are: public: off, private: 8080 (no TLS).
The default configuration provided with jitsi-meet results in:
public on 443 (TLS), private on 8080 (no TLS)
Adds a redirection (HTTP 301) for /colibri/* and /about/* from the public interface to the private one.

Rest configuration

---

lib/logging.properties
src/main/java/org/jitsi/videobridge/xmpp/ComponentImpl.java

The current implementation causes all XMPP traffic to be printed to INFO, instead of the intended DEBUG level. Verbosity should reduced.

logd() should log to debug, not info.

---

.gitignore
openfire/pom.xml
openfire/src/web/WEB-INF/web.xml
pom.xml
src/assembly/native-linux-32.xml
src/assembly/native-linux-64.xml
src/assembly/native-macosx.xml
src/assembly/native-windows-32.xml
src/assembly/native-windows-64.xml

This PR contains two dependent commits: one makes the native libraries as used by the Videobridge available via Maven. The second commit adds a Maven structure to the Openfire plugin that ships with JVB (leaving the existing Ant file intact, for the time being).

Native libraries via Maven + Mavenizing Openfire plugin

---

src/main/java/org/jitsi/videobridge/cc/SimulcastController.java

Anything that's not a desktop Chrome browser (e.g. FF, mobile app) does
not support simulcast atm. Attempting to rewrite the TL0PICIDX of these
non-scalable streams results in the logs being spammed with the message
"Failed to set the VP8 TL0PICIDX". This commit fixes this by not
attempting to rewrite the TL0PICIDX of non-scalable streams.

fix: Do not attempt to rewrite the TL0PICIDX of non-scalable streams.

---

src/main/java/org/jitsi/videobridge/cc/BitrateController.java

Currently the FF webrtc engine ignores our bandwidth probing (https://bugzilla.mozilla.org/show_bug.cgi?id=1362450), so we want to disable bandwidth probing for FF. FF also does not support RTX. This method will be used by the bridge to determine whether the destination endpoint has RTX or not. If not, then that would indicate a FF destination endpoint and it will disable adaptivity for that endpoint.
This depends on https://github.com/jitsi/libjitsi/pull/307

fix: Disable bandwidth probing for endpoints that do not support RTX (FF).

---

src/main/java/org/jitsi/videobridge/Videobridge.java

when no authorizedSourcePattern is configured. Fixes a unit test failure
reported by Devin Wilson on the mailing list.

fix: Doesn't accept COLIBRI IQs with focus==null

---

src/assembly/native-linux-32.xml
src/assembly/native-linux-64.xml
src/assembly/native-macosx.xml
src/assembly/native-windows-32.xml
src/assembly/native-windows-64.xml

The jar files that contain the native libraries used to be 'flat' archives (all native library files were in the root of the archive). This changes unintentionally. That's being corrected here.

Native jars should be flat

---

pom.xml
src/main/java/org/jitsi/videobridge/eventadmin/callstats/CallStatsConferenceStatsHandler.java

The callstats also had an update for some metrics not appearing on the
dashboard.

Updates callstats and wrong data sent.

---

pom.xml
src/main/java/org/jitsi/videobridge/RtpChannel.java

This reverts commit c6095487f482b5cad21990cbd41c1c6970f7b166 which is unnecessary AND fine tunes the RBE traces. It depends on https://github.com/jitsi/libjitsi/pull/374.

logs: Fine tunes the RBE traces.

---

src/main/java/org/jitsi/videobridge/Conference.java
src/main/java/org/jitsi/videobridge/Endpoint.java
src/main/java/org/jitsi/videobridge/EndpointConnectionStatus.java
src/main/java/org/jitsi/videobridge/EndpointMessageTransport.java
src/main/java/org/jitsi/videobridge/EventFactory.java

The event will be fired when either WebSocket or SCTP endpoint message transport is ready. This will fix broadcasting of the initial endpoint connection status when WebSockets are used (and random build failures).

ref(events): introduce MSG_TRANSPORT_READY_TOPIC

---

resources/install/debian/postinst

java.nio.file.FileSystemException: /etc/jitsi/videobridge: Operation not permitted

Fixes 'Operation not permitted' on startup.

---

doc/rest-colibri.md
pom.xml
src/main/java/org/jitsi/videobridge/VideoChannel.java
src/main/java/org/jitsi/videobridge/rest/JSONDeserializer.java
src/main/java/org/jitsi/videobridge/rest/JSONSerializer.java

according with next issue
https://github.com/jitsi/jitsi-videobridge/issues/568
added possibility to serialize / de-serialize rtcp-fb parameters for REST (colibri) protocol.

added rtcp-fb payload type parameters field suppoty to rest protocol

---

src/main/java/org/jitsi/videobridge/Conference.java
src/main/java/org/jitsi/videobridge/Endpoint.java

Commit 2a15aa43c40 introduces a bug which fails to expire endpoints,
which results in leaks. This attempts to resolve this problem.

fix: Fixes expiration of endpoints.

---

src/main/java/org/jitsi/videobridge/cc/BitrateController.java

This is a supplementary commit to https://github.com/jitsi/jitsi-videobridge/pull/622.

logs: Record when the bridge is oversending.

---

resources/install/debian/control

The postinstall script calls out to sysctl: https://github.com/jitsi/jitsi-videobridge/blob/master/resources/install/debian/postinst#L150
which is foung in the procps package.
As unusual as it may sound, there are systems which do not have the procps package installed,
such as the debian-slim Docker images.

debian: add missing dependency on procps

---

resources/mvn-exec.sh

The mvn-exec.sh script can be used to run from source. This PR removes most of the old options but that shouldn't break anything as the script is mostly used for debugging.

ref: Simplifies the mvn-exec.sh script.

---

src/main/java/org/jitsi/videobridge/octo/OctoRelay.java
src/main/java/org/jitsi/videobridge/octo/OctoRelayService.java

Many cloud providers, like `Scaleway` do not allows to bind directly to public ip, for those relayId may be configurable and can be different from bindAddress. 
E.g. bind to 0.0.0.0:42000 but relayId will be `11.11.11.11:42000`.

Configurable relayId

---

doc/simulcast.md

I found a minor typo on `doc/simulcast.md` (line 136). Thanks for the awesome opensource :)

Fix typo on simulcast.md

---

src/main/java/org/jitsi/videobridge/AbstractEndpoint.java
src/main/java/org/jitsi/videobridge/Conference.java
src/main/java/org/jitsi/videobridge/Endpoint.java
src/main/java/org/jitsi/videobridge/EndpointMessageBuilder.java

Start tracking which endpoints are 'selected' and notify the endpoints
if they just transitioned from being selected by no participants
to being selected by at least one or vice versa.

Notify endpoints if they are currently selected

---

pom.xml
src/main/java/org/jitsi/videobridge/IceUdpTransportManager.java
src/main/java/org/jitsi/videobridge/Videobridge.java

When the bridge is being closed, resources should be released explicitly. This commit closes down harvesters, which in turn unbinds from the network interface.

fix: release resources when shutting down.

---

src/main/java/org/jitsi/videobridge/IceUdpTransportManager.java

When the single-port UDP harvester is available, there's no need to offer the dynamic-port UDP harvester to the client, as there's little chance that the client would have a different result using either.
However, this does not mean that when _not_ using single-port UDP harvester, the dynamic-port UDP harvester should be forcefully _enabled_. The dynamic-port harvester is enabled by default. By forcefully enabling it, its configuration option (`org.ice4j.ice.harvest.USE_DYNAMIC_HOST_HARVESTER`) is overridden, which is undesirable (as it prevents one from disabling this harvester).

Prevent forcefully enabling the dynamic host harvester

---

pom.xml
resources/link-conditioner.sh
src/main/java/org/jitsi/videobridge/Conference.java
src/main/java/org/jitsi/videobridge/VideoChannel.java
src/main/java/org/jitsi/videobridge/Videobridge.java
src/main/java/org/jitsi/videobridge/cc/BitrateController.java
src/main/java/org/jitsi/videobridge/stats/VideobridgeStatistics.java

This PR adds three new stats:
- total participant-seconds
- total loss-limited participant-seconds (which is the total number of
seconds that the bandwidth is limited due to loss.
- total loss-degraded participant seconds (which is the total number of
seconds that the bandwidth is degraded due to loss.
Depends on https://github.com/jitsi/libjitsi/pull/426

feat: Adds new stats to track bwe limited-seconds and participant-seconds.

---

pom.xml
src/main/java/org/jitsi/videobridge/AudioChannel.java
src/main/java/org/jitsi/videobridge/Channel.java
src/main/java/org/jitsi/videobridge/Content.java
src/main/java/org/jitsi/videobridge/RtpChannel.java
src/main/java/org/jitsi/videobridge/SctpConnection.java
src/main/java/org/jitsi/videobridge/VideoChannel.java
src/main/java/org/jitsi/videobridge/Videobridge.java
src/main/java/org/jitsi/videobridge/octo/OctoChannel.java
src/main/java/org/jitsi/videobridge/osgi/JvbBundleConfig.java
src/main/java/org/jitsi/videobridge/stats/MucStatsTransport.java
src/main/java/org/jitsi/videobridge/stats/PubSubStatsTransport.java
src/main/java/org/jitsi/videobridge/stats/StatsManager.java
src/main/java/org/jitsi/videobridge/stats/StatsManagerBundleActivator.java
src/main/java/org/jitsi/videobridge/xmpp/ClientConnectionImpl.java
src/main/java/org/jitsi/videobridge/xmpp/ComponentImpl.java
src/main/java/org/jitsi/videobridge/xmpp/XmppCommon.java

Publishes statistics as presence in a MUC (a-la jibri).
Supports COLIBRI, health checks and the rest of the functionality
exposed through the XMPP component through an XMPP client connection.

feat: Adds an XMPP client connection interface.

---

src/main/java/org/jitsi/videobridge/osgi/JvbBundleConfig.java

Loads the REST bundle before the Videobridge bundle, because Jetty needs
to bind on port 443 before ice4j's TCP harvester does. When Videobridge
loads it starts its health checks, which results in the TCP harvester
binding.

fix: Fixes the order in which TCP/443 is bound.

---

pom.xml

Fixes tests, after updating libjitsi.

Updates ice4j to 2.0.0-20181213.100259-20.

---

src/main/java/org/jitsi/videobridge/EndpointMessageTransport.java
src/main/java/org/jitsi/videobridge/SctpConnection.java
src/main/java/org/jitsi/videobridge/WebRtcDataStream.java
src/main/java/org/jitsi/videobridge/WebRtcDataStreamListener.java

Starting in Chrome M69 it will no longer release WebRTC Data Channels when the "data" content is [rejected] on ICE restart. I suspect it's this [commit in WebRTC] which waits for the channels to be gracefully closed (but haven't bisected that to confirm). Because the conference is moved to new bridge it will never happen. So the stack correctly resets the SCTP transport layer, but keeps the SID = 0 used by the bridge and does not allow it to open it's data channel on SID = 0 again.
As a workaround (because it's to late to file a bug and have a fix in the stable) I was thinking about moving opening of the data channel to the client, so that it know which next SID is free. This also makes the JVB a bit more elastic for other clients, because should accommodate both cases where JVB opens …

Use WebRTC data channels opened by the client

---

src/main/java/org/jitsi/videobridge/cc/AdaptiveTrackProjection.java
src/main/java/org/jitsi/videobridge/cc/AdaptiveTrackProjectionContext.java
src/main/java/org/jitsi/videobridge/cc/GenericAdaptiveTrackProjectionContext.java
src/main/java/org/jitsi/videobridge/cc/RtpState.java
src/main/java/org/jitsi/videobridge/cc/vp8/VP8AdaptiveTrackProjectionContext.java
src/main/java/org/jitsi/videobridge/cc/vp8/VP8FrameProjection.java
src/main/java/org/jitsi/videobridge/xmpp/ComponentImpl.java
src/main/java/org/jitsi/videobridge/xmpp/XmppCommon.java

In theory the media engine can switch from sending simulcast -> non-simulcast on the fly and without additional signaling (either intentionally, or unintentionally due to a bug for example). The JS code can also activate/de-activate simulcast on the fly without signaling that back to the bridge (that would definitely be due to a bug). We recently observed for some scrambling video issues with the latest bridge and suspected that a bug in the JS code was causing the media engine to switch from doing simulcast -> not simulcast without signaling that to the bridge. This PR implements adaptive track projection context switches and treats the change from simulcast -> non-simulcast stream as a codec switch. Further analysis showed that there this wasn't an issue in the client and that there's …

Implements adaptive track context switching with some other fixes.

---

src/main/java/org/jitsi/videobridge/Endpoint.java
src/main/java/org/jitsi/videobridge/cc/AdaptiveTrackProjection.java
src/main/java/org/jitsi/videobridge/cc/AdaptiveTrackProjectionContext.java
src/main/java/org/jitsi/videobridge/cc/BitrateController.java
src/main/java/org/jitsi/videobridge/cc/GenericAdaptiveTrackProjectionContext.java
src/main/java/org/jitsi/videobridge/cc/vp8/VP8AdaptiveTrackProjectionContext.java
src/main/java/org/jitsi/videobridge/cc/vp8/VP8Frame.java
src/main/java/org/jitsi/videobridge/cc/vp8/VP8FrameProjection.java
src/main/java/org/jitsi/videobridge/cc/vp8/VP8QualityFilter.java

I did not get as far as I wanted to with this (we still do not preserve the PacketInfo instance, meaning we lose the receivedTime/timeline), but it is a step in the right direction (we avoid packet conversion) and I think the next step will be a pretty big change.
I think we can actually change this flow a bit to work such that, rather than caching all packets, it holds only those that it may want in incomplete frames and can then release them.  So instead of copying and caching all packets of which we may only use some, we can just hold some pending packets until we discover we do (or don't) need them.  This is along the lines of the 'jitter buffer scheme' idea I had for this class before.  We'll probably need to talk with george about that change, but we can discuss it more tomorrow.

Port BitrateController

---

src/main/java/org/jitsi/videobridge/DtlsTransport.java
src/main/java/org/jitsi/videobridge/Endpoint.java
src/main/java/org/jitsi/videobridge/IceTransport.java

ICE/DTLS may take a long time (>1s) and if we keep caching packets
coming from other endpoint in the conference we:
1. Might fill the SRTP cache
2. Will cause a spike in bitrate once we connect (while videos are probably
not decodable because yet because there's no keyframe)
3. Might cause problems with the timing of the audio playback

fix: Do not accept packets until ICE and DTLS connect.

---

src/main/java/org/jitsi/videobridge/Conference.java
src/main/java/org/jitsi/videobridge/octo/OctoEndpoint.java
src/main/java/org/jitsi/videobridge/octo/OctoEndpoints.java

Expires OctoEndpoints if a request for a new local endpoint with the
same ID is received.

Fixes moving endpoints between bridges with Octo

---

src/main/java/org/jitsi/videobridge/cc/BitrateController.java

Right now we require a 15% (configurable) change in the bwe in order to
update the bitrate allocation. This is an ugly hack to prevent too many
resolution/UI changes in case the bridge produces too low bandwdith
estimate, at the risk of clogging the receiver's pipe.
The code prevented not only downscaling, but also upscaling, which is
problematic: Suppose that the target bitrate is 2.5Mbps, and that the
last bitrate allocation was performed with a 2.4Mbps bandwidth esitmate.
The bridge keeps probing and, suppose that, eventually the bandwidth
estimate reaches 2.6Mbps, which is plenty to accomodate the target
bitrat; but the minimum bandwidth estimate that would trigger a new
bitrate allocation is 2.4Mbps + 2.4Mbps * 15% = 2.76Mbps.

Unthrottle bitrate allocation updates when the bandwidth increases

---

pom.xml
src/main/java/org/jitsi/videobridge/SctpConnection.java
src/main/java/org/jitsi/videobridge/cc/AdaptiveTrackProjection.java
src/main/java/org/jitsi/videobridge/cc/BandwidthProbing.java
src/main/java/org/jitsi/videobridge/cc/BitrateController.java

Related PR https://github.com/jitsi/libjitsi/pull/483
This PR addresses an issue caused by https://github.com/jitsi/jitsi-videobridge/pull/870 where the bridge logs fill-up the disk because it prints multiple lines for every packet that it processes.

Debug logging of packet mishandling round 2

---

src/main/java/org/jitsi/videobridge/Conference.java

Without the grace period the conference might be expired prematurely. We
observed the following exception:
```
JVB 2019-08-05 12:30:39.031 INFO: [47] org.jitsi.videobridge.VideobridgeExpireThread.log() Running expire()
JVB 2019-08-05 12:30:39.031 INFO: [48] org.jitsi.videobridge.Videobridge.log() create_conf,[id=4821bc9b84c7418d gid=null name=null] logging=false
JVB 2019-08-05 12:30:39.031 INFO: [47] org.jitsi.videobridge.VideobridgeExpireThread.log() Conference 4821bc9b84c7418d should expire, expiring it
JVB 2019-08-05 12:30:39.032 SEVERE: [48] org.jitsi.videobridge.health.Health.log() Health check failed in 1ms:
java.lang.NullPointerException
at org.jitsi.videobridge.ConferenceSpeechActivity.endpointsChanged(ConferenceSpeechActivity.java:392)
at …
```

Add a grace period before a conference is expired.

---

doc/rest.md

Disabling this option partially addresses an issue where the certbot cronjob installed by jitsi-meet is unable to bind to port 80.

Documentation for feature introduced by PR #722.

---

src/main/java/org/jitsi/videobridge/shim/ChannelShim.java
src/main/java/org/jitsi/videobridge/shim/ContentShim.java

I'm migrating to `JVB 2.0` and I think default visibility of changed members was introduced non-intentionally.
If default visibility was design decision please let me know.

Adjust shim's member visibility.

---

src/test/java/org/jitsi/videobridge/xmpp/MediaStreamTrackFactoryTest.java

Always sets the SVC flags as intended.

fix: Fixes the media stream tracks factory tests

---

src/main/java/org/jitsi/videobridge/shim/ConferenceShim.java

Fixed probably wrong `Colibri` generation for data channels (at least `JVB 1.0` put data channel into sctp connection in IQ).

Fixed Colibri description of data channels.

---

src/main/java/org/jitsi/videobridge/shim/ChannelShim.java

In `JVB 1.0` `conference.describeDeep` produce channel's description with `SSRC` information. 
Example:
```
<channel endpoint="#1" expire="15" id="e352c15176eab2c0" channel-bundle-id="#1" rtp-level-relay-type="translator">
...
<source xmlns="urn:xmpp:jingle:apps:rtp:ssma:0" ssrc="2481496264" />
<ssrc>4228755975</ssrc>
...
</channel>
```
In `JVB 2.0` `<ssrc>` attribute is missing.
I don't know if it's intentional or not. Since it might be accidental missing information here is PR which adds it back.

Fill in SSRCs field in channel IQ.

---

src/main/java/org/jitsi/videobridge/Conference.java
src/main/java/org/jitsi/videobridge/EventFactory.java

In `JVB 1.0` there was an `CHANNEL_EXPIRED_TOPIC`. 
I've used it to find out when endpoint is expired, by handler like this:
```
final void onChannelExpired(Object eventSource, String eventTopic, Event event) {
Channel channel = (Channel) eventSource;
if (channel.getEndpoint().isExpired()) {
// endpoint expiration handling here
}
}
```
The `CHANNEL_EXPIRED_TOPIC` event was removed from `JVB 2.0` as there is no more the notion of `CHANNEL` in `JVB 2.0` (shim layer is not counted).
AFAIK, `Endpont` is now the primary entity in a conference, so it make sense to have dedicated event for endpoint expiration.

Added endpoint expire event.

---

src/main/java/org/jitsi/videobridge/rest/RESTBundleActivator.java
src/main/java/org/jitsi/videobridge/rest/stats/Stats.java
src/main/java/org/jitsi/videobridge/rest/stats/StatsApp.java
src/main/java/org/jitsi/videobridge/util/StatsManagerProvider.java

missed these overall bridge stats (used mainly when pushing to datadog)

bring back overall stats

---

src/main/java/org/jitsi/videobridge/DtlsTransport.java

The `setup` field was properly described in `JVB 1.0`, but not in `JVB 2.0`:
https://github.com/jitsi/jitsi-videobridge/blob/838e190c4dcf0ca5b94a4065780a59a82792a744/src/main/java/org/jitsi/videobridge/IceUdpTransportManager.java#L1321-L1327
According to [this document](https://xmpp.org/extensions/xep-0320.html) role spelling must be lower case:
```
<xs:attribute name='setup' use='required'/>
<xs:simpleType>
<xs:restriction base='xs:NCName'>
<xs:enumeration value='active'/>
<xs:enumeration value='passive'/>
<xs:enumeration value='actpass'/>
<xs:enumeration value='holdconn'/>
<xs:annotation>
<xs:documentation>
the 'holdconn' value is not used and included only for completeness.
</xs:documentation>
</xs:annotation>
</xs:restriction>
</xs:simpleType>
</xs:attribute>
```

Fill proper DTLS setup value when transport is described.

---

src/main/java/org/jitsi/videobridge/IceTransport.java

Due to ice control role conflict resolution Agent's role might be different from what was used during initialization. It's better to poll current state when debug info object is filled.

Fixed controlling value in `IceTransport` debug state.

---

src/main/java/org/jitsi/videobridge/AbstractEndpoint.java
src/main/java/org/jitsi/videobridge/Conference.java
src/main/java/org/jitsi/videobridge/DtlsTransport.java
src/main/java/org/jitsi/videobridge/Endpoint.java
src/main/java/org/jitsi/videobridge/health/Health.java
src/main/java/org/jitsi/videobridge/shim/ConferenceShim.java
src/main/java/org/jitsi/videobridge/shim/ContentShim.java
src/main/java/org/jitsi/videobridge/shim/VideobridgeShim.java

This is the first step in restoring ability to control `JVB 2.0` ICE role during connection establishment.
`JVB 1.0` had ability to be either controlling/controlled agent based on `initiator` field in `IQ`.
Currently I'm suffering from [ICE role conflict issue](https://github.com/jitsi/ice4j/pull/187), but even when it is resolved there still be an issue with Firefox (I'm still investigating that Firefox bug).
So I'd like to have an explicit control over `JVB 2.0` ICE role, so I'll not rely on role conflict resolution implementation. This PR is first step to bringing back configurable ICE role of `JVB`.

Ability to set ICE role during DtlsTransport creation.

---

pom.xml
src/main/java/org/jitsi/videobridge/Main.java

The lack of this was causing Jetty to find an old slf4j version (brought in by dependencies) and throw exceptions, which was breaking the REST API.

tell jetty to use jul

---

src/main/java/org/jitsi/videobridge/rest/annotations/EnabledByConfig.java
src/main/java/org/jitsi/videobridge/rest/filters/ConfigFilter.java
src/main/java/org/jitsi/videobridge/rest/root/colibri/ColibriResource.java

this change allows a default value to be passed to the EnabledByConfig
annotation and, in the case of colibri resources, sets that default
value to true (enabled)

default the colibri rest resource to enabled

---

src/main/java/org/jitsi/videobridge/rest/root/colibri/stats/Stats.java
src/test/java/org/jitsi/videobridge/rest/root/colibri/stats/StatsTest.java

return a json object, containing only the stats from
VideobridgeStatistics

restore old behavior of /colibri/stats rest endpoint

---

src/main/java/org/jitsi/videobridge/Conference.java
src/main/java/org/jitsi/videobridge/stats/VideobridgeStatistics.java

from what i can tell, `getEndpointCount` used to return only the count
of local (i.e. non-octo) endpoints, as we used to keep `OctoEndpoint`s
and `Endpoint`s in different data structures.  i believe the other code
which calls `getEndpointCount` _is_ looking for a total endpoint count
(not just a local one) but i'm hoping @bgrozev can help clarify things
there, as this code didn't exist in 1.0.  to minimize the change, i've
added a new explicit `getLocalEndpointCount` and had the stats call
that, leaving the other code alone.
cc @aaronkvanmeerten

change VideobridgeStatistics to report just the local endpoint count

---

src/assembly/linux-x64-bin-archive.xml
src/assembly/linux-x86-bin-archive.xml
src/assembly/macosx-bin-archive.xml
src/assembly/windows-x64-bin-archive.xml
src/assembly/windows-x86-bin-archive.xml

archives
i took a look at also renaming the videobridge jar to `jitsi-videobridge.jar`, but that's a bit trickier.  so will save that for (maybe) another PR.

don't include with jitsi-videobridge-with-dependencies jar in the

---

src/main/java/org/jitsi/videobridge/cc/vp8/VP8AdaptiveTrackProjectionContext.java

This will fix the performance bottleneck from clearing old entries from the VP8 frame projection map.

Optimize vp8 frame projection map

---

src/assembly/linux-x64-bin-archive.xml
src/assembly/linux-x86-bin-archive.xml
src/assembly/macosx-bin-archive.xml
src/assembly/windows-x64-bin-archive.xml
src/assembly/windows-x86-bin-archive.xml

the thinking here was that it would be better to be able to assume a specific name for the videobridge jar (e.g. [this](https://github.com/jitsi/jitsi-videobridge/pull/951) PR could be made to use a specific filename instead of a wildcard for the jvb jar).  we considered the idea of having a versioned-jar filename with a symlink `jitsi-videobridge.jar` pointing to it, but decided that the version is available via other means so this was unnecessary.

always rename the jvb jar to jitsi-videobridge.jar in the archive

---

pom.xml

It looks like the property `jitsi-desktop.version` is not used anywhere else in `pom.xml` and could be removed.

Remove unused property in pom.xml

---

pom.xml

I believe these two dependencies supposed to have `<groupId>${project.groupId}</groupId>` the same as other `org.jitsi`'s dependencies.

Use ${project.groupId} instead of org.jitsi in pom.xml

---

resources/install/linux-64/jvb.sh
resources/install/linux/jvb.sh
resources/install/macosx/jvb.sh

individually
I often check `ps` to verify bridge is running and to check the command-line arguments which were passed. but right now we pass every file from the `lib` dir individually to the classpath, which makes it difficult to parse.  Instead, we can pass the directory name and achieve the same result.  Soon I'll be adding another argument for the new config file, so it will be even more useful to make this more readable.
Before this change, when checking `ps aux | grep videobridge` the result will contain:
> java -agentpath:/home/bbaldino/YourKit-JavaProfiler-2019.8/bin/linux-x86-64/libyjpagent.so=probe_disable=*,delay=10000,port=3478,listen=all -Xmx3072m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -Djava.library.path=/usr/share/jitsi-videobridge/lib/native/linux-64 …

pass the lib dir as the classpath instead of every file in it

---

build.xml

verified that the `jitsi-videobridge.jar` built via `ant -Dlabel=XX rebuild deb-64` contains `reference.conf`

Include resources in deb

---

src/main/java/org/jitsi/videobridge/Endpoint.java
src/main/java/org/jitsi/videobridge/octo/OctoRelay.java
src/main/java/org/jitsi/videobridge/octo/OctoTentacle.java

when i was trying to debug some octo issues i found myself wishing we had some extra logs to make things clear.  i suspect we may be removing a relay handler prematurely (something that could be coming from the shims which have changes in 2.0, so would explain why we're not seeing it in old bridge)

Octo logging

---

pom.xml
src/main/java/org/jitsi/videobridge/Endpoint.java
src/main/java/org/jitsi/videobridge/EndpointConnectionStatus.java
src/main/java/org/jitsi/videobridge/shim/ChannelShim.java

The `JVB 1.0` [allowed to update media direction of `RTPChannel`](https://github.com/jitsi/jitsi-videobridge/blob/c29af045ca7081dce457ebd25a025248cfda3a67/src/main/java/org/jitsi/videobridge/RtpChannel.java#L1381-L1399) during it's lifetime either directly or [via colibri](https://github.com/jitsi/jitsi-videobridge/blob/c29af045ca7081dce457ebd25a025248cfda3a67/src/main/java/org/jitsi/videobridge/Videobridge.java#L953-L954) request.
This ability was used in a project I'm working on to implement hold functionality: leave connection between client and JVB, but do not forward media to a client.
I hope it was not intentional design decision to remove such functionality from `JVB 2.0`, so I've implemented it for `JVB 2.0`.

Updateable media direction

---

src/main/java/org/jitsi/videobridge/util/config/ConfigSupplierSettings.java
src/main/java/org/jitsi/videobridge/util/config/JvbConfig.java
src/test/java/org/jitsi/testutils/ConfigSetup.java

i noticed this when working on another PR when i tried setting the
command-line args supplier to include the args given in main.  the
problem was that, since JvbConfig loaded the config in a static block,
any access on JvbConfig would trigger it--this includes setting a
supplier.  for the command-line args case, this means that when you
called JvbConfig.commandLineArgsSupplier = ..., the config would load
and log that no command line args were present (since the assignment was
not yet complete) which was misleading.  it also had the annoying
behavior of dumping any default-loaded config during tests when the
suppliers were overriden.
by separating that config out, we can manipulate the config source
suppliers without triggering a loading of the config, which makes more
sense.

move the configuration of config source suppliers to another file

---

src/main/java/org/jitsi/videobridge/IceTransport.java

This lets the derived class know when ICE consent is updated.

Add a protected method onIceConsentUpdated to IceTransport.

---

src/main/java/org/jitsi/videobridge/shim/ChannelShim.java

in JVB 2.0 in coparison with JVB 1.0 sourceGroup attribute is missing.

[ChannelShim::describe] Fill sourceGroup in channel IQ

---

pom.xml
src/main/java/org/jitsi/videobridge/AbstractEndpoint.java
src/main/java/org/jitsi/videobridge/Endpoint.java
src/main/java/org/jitsi/videobridge/EndpointConnectionStatus.java
src/main/java/org/jitsi/videobridge/shim/ChannelShim.java
src/test/java/org/jitsi/videobridge/EndpointConnectionStatusTest.java

Fun fact: `Instant.MIN`, which we use for our definition of `NEVER` is unable to be converted to a number of milliseconds-since-epoch.  This is probably good for `NEVER`, but broke some things here, so had to migrate away from the usage of the old properties and use `Instant` everywhere.
I think `EndpointConnectionStatus` could really use a unit test for its logic, but it'll need to be refactored so we can swap in a fake executor service, etc. so left that for future work.

Move to new PacketIOActivity fields based on Instant

---

pom.xml
src/main/java/org/jitsi/videobridge/Videobridge.java
src/main/java/org/jitsi/videobridge/osgi/BundleConfig.java
src/main/java/org/jitsi/videobridge/osgi/ConfigurationActivator.java
src/test/java/org/jitsi/videobridge/BridgeShutdownTest.java

This change installs the legacy configuration service shim defined in jicoco  as the supplier for `ConfigurationService`, removing the need for libjitsi in JVB 💥  
Depends on https://github.com/jitsi/jicoco/pull/61

use new legacy config service shim, remove libjitsi dependency

---

.gitignore
src/main/java/org/jitsi/videobridge/octo/OctoTentacle.java

We used to only trigger an update when the list of endpoint change. We also need to call it when the tracks of an existing endpoint change (which happens when presenter mode is enabled or disabled in jitsi-meet).

Updates the bitrate controller when an OctoEndpoint's tracks change.

---

src/main/java/org/jitsi/videobridge/Main.java
src/main/java/org/jitsi/videobridge/Videobridge.java

the config library caches the results, so to see new values we need to
reload.

force a reload of the config after setting system properties

---

src/main/java/org/jitsi/videobridge/Videobridge.java

The new config converts .properties values into a HOCON object, which is slightly lossy compared to a properties file. For example, in a properties like so:
```
a.b.c = true
a.b.c.d = 42
```
Is fine, but in a HOCON object there's an issue: `a.b.c` has to be one of the two values (a boolean or an object), so the value of `a.b.c` ends up as an object, making it impossible to test as a boolean.
This scenario was happening with `org.jitsi.videobridge.rest`.  Soon, we'll port the handling of the API properties to new config, but for now we'll change the value so there's no conflict.

change rest api sys prop name

---

src/main/java/org/jitsi/videobridge/AbstractEndpoint.java
src/main/java/org/jitsi/videobridge/Endpoint.java
src/main/java/org/jitsi/videobridge/octo/OctoEndpoint.java

https://github.com/jitsi/jitsi-videobridge/pull/1005 caused an exception because we subscribed to encodingManager notifications before the constructor completed.

Fix encodings manager exception

---

pom.xml
src/main/java/org/jitsi/videobridge/cc/GenericAdaptiveTrackProjectionContext.java

Since we'll never see one.
(This updates JVB for recent JMT API changes.)

When projecting VideoRtpPackets that aren't ParsedVideoPackets, don't wait for keyframes.

---

lib/logging.properties
resources/install/debian/control
resources/install/debian/postinst

Not sure which one to merge first, I think tests that test the debian package deployment will fail till we have all 3 components jitsi-meet, jicofo and jvb changes merged.
Once this is merged I will cherry-pick it for jvb2.
https://github.com/jitsi/jitsi-meet/pull/4956
https://github.com/jitsi/jicofo/pull/413

Migrate to using mucs for jvb

---

src/main/java/org/jitsi/videobridge/cc/AdaptiveTrackProjection.java

Add targetSsrc and srcEpId to logger.
Log "no source information" and "no encoding information" errors separately.

AdaptiveTrackProjection log enhancements.

---

src/main/java/org/jitsi/videobridge/Endpoint.java

Not sure if this PR is valid according to JVB design, but at least it could serve as my question regarding proper scenario handling described below:
I want to have multiple video streams from single endpoint, for example in scenario when both screen sharing and camera are turned on.
There are two options to achieve this via Colibri request:
1. Have single endpoint with multiple video channels each having it's own ssrc/ssrc groups signaled;
2. Have single endpoint with single video channel, but multiple ssrcs/ssrc groups signaled for that channel.
1 option does not properly work due to current `recreateMediaStreamTracks` implementation, with this PR both options should work well.
For me it would be convenient if option 1 also work. 
What do you think about the change (it should not break …

Populate source and source groups from all channel when tracks are re-created.

---

resources/install/debian/control
resources/install/debian/postinst

* Migrates to use mucs by default.
* Disables just component and leaves defaults.

Migrate to using mucs for jvb (#1009)

---

pom.xml
src/main/java/org/jitsi/videobridge/AbstractEndpoint.java
src/main/java/org/jitsi/videobridge/Conference.java
src/main/java/org/jitsi/videobridge/DtlsTransport.java
src/main/java/org/jitsi/videobridge/ice/IceTransport.java
src/main/java/org/jitsi/videobridge/shim/ConferenceShim.java

This cleans up a couple things:
1) The 'manual' log prefix we had in IceTransport (which was needed because we previously couldn't add log context to a logger after it was created)
2) Replaces some usages of manual `isDebugEnabled` checks with the provider-based logger methods
3) Adds 'stats id' and 'display name' to an endpoint's log context (when non-null)
Depends on https://github.com/jitsi/jitsi-utils/pull/38

LogContext improvements

---

pom.xml

This adds a new method for building a fat jar which correctly concatenates `reference.conf` files if there are multiple (which is the case since JVB and JMT have them).
Although building the fat jar only took ~3 seconds longer on my machine, I made it off by default.  It can be built by passing `-P buildFatJar` to maven.
`maven-assembly-plugin` had some support for this, but it didn't support concatenating the files for the final jar, so we no longer use it for building the fat jar, and use `maven-shade-plugin` instead which is recommended in the `maven-assembly-docs`:
```
Note that jar-with-dependencies provides only basic support for uber-jars. For more control, use the Maven Shade Plugin.
```
[here](https://maven.apache.org/plugins/maven-assembly-plugin/descriptor-refs.html#jar-with-dep …

Combine reference conf correctly when building a fat jar

---

src/main/java/org/jitsi/videobridge/cc/AdaptiveTrackProjection.java
src/main/java/org/jitsi/videobridge/cc/BitrateController.java

by the bitratecontroller to avoid any out-of-sync issues.
There existed a race between creating an `AdaptiveTrackProjection` and being notified of a new payload type that resulted in the `AdaptiveTrackProjection` not knowing of a payload type and logging `AdaptiveTrackProjection.getContext#278: No payload type object signaled for payload type...`.  This change removes the chance for the two payload type maps (one in `BitrateController`, one in `AdaptiveTrackProjection`) getting out of sync by using only a single map.

have adaptivetrackprojection refer to the same map of payload types used

---

src/main/java/org/jitsi/videobridge/Endpoint.java
src/main/java/org/jitsi/videobridge/cc/BitrateController.java

This log isn't completely unexpected, and can happen for a brief period when an endpoint first joins (before it's updated about all other endpoints in the conference), so reduce the log level and track the number of occurrences in a stat.

Reduce log level of 'unknown ssrc' log in BitrateController

---

src/main/java/org/jitsi/videobridge/Videobridge.java
src/main/java/org/jitsi/videobridge/rest/root/colibri/debug/Debug.java

This avoids having to do 2 API calls during testing, first get the conference id and then get the full description of the call.

Adds a query param to the main debug call in the colibri http api.

---

src/main/java/org/jitsi/videobridge/cc/vp8/VP8AdaptiveTrackProjectionContext.java
src/main/java/org/jitsi/videobridge/cc/vp8/VP8FrameMap.java

Rather than throwing an exception.
This is necessary because we now index frames in the map by picture ID rather than by timestamp.
Note this is *not* the same as https://github.com/jitsi/jitsi-videobridge/pull/1077; it's addressing a different (though related) problem.

Log an error, and fail frame insertion, if a frame in the frame map doesn't match.

---

pom.xml

(I don't think we need a corresponding JMT bump for https://github.com/jitsi/jitsi-media-transform/pull/223; it just has a comment update and a RTP version update, and this Maven RTP version wins.)

Bump RTP version.

---

src/main/java/org/jitsi/videobridge/Endpoint.java

When endpoint A in a conference permanently looses connection with JVB it is eventually expired by this code due to lack of network activity: 
https://github.com/jitsi/jitsi-videobridge/blob/c5b5f463cae3ad1e8548678d4fa7ff16e9918cad/src/main/java/org/jitsi/videobridge/VideobridgeExpireThread.java#L157-L164
But all the ChannelShims which were corresponded to Endpoint A are not expired and not removed from [`ConferenceShim.contents`](https://github.com/jitsi/jitsi-videobridge/blob/c5b5f463cae3ad1e8548678d4fa7ff16e9918cad/src/main/java/org/jitsi/videobridge/shim/ConferenceShim.java#L55-L58)/[`ContentShim.channels`](https://github.com/jitsi/jitsi-videobridge/blob/c5b5f463cae3ad1e8548678d4fa7ff16e9918cad/src/main/java/org/jitsi/videobridge/shim/ContentShim.java#L66-L69). …

Fixed Endpoint leak caused by ChannelShims not being removed from ConerenceShim.

---

src/main/java/org/jitsi/videobridge/EndpointConnectionStatus.java

I suspect this was the cause of the otherwise-inexplicable NPE in `EndpointConnectionStatus.handleEvent`.
Note the addition of `synchronized` blocks changed indentation, so you may wish to review the version of the diff ignoring whitespace changes.

Synchronize access to inactiveEndpoints list.

---

src/main/java/org/jitsi/videobridge/cc/AdaptiveTrackProjection.java

possible exception in LogContext  when use ImmutableMap.copyOf(context), if source.getOwner() is null

AdaptiveTrackProjection log: null value check for srcEpId

---

pom.xml
src/main/java/org/jitsi/videobridge/cc/AdaptiveTrackProjection.java
src/main/java/org/jitsi/videobridge/cc/vp8/VP8AdaptiveTrackProjectionContext.java
src/main/java/org/jitsi/videobridge/cc/vp8/VP8FrameMap.java

This is https://github.com/jitsi/jitsi-videobridge/pull/1106 but with the branch name changed to match https://github.com/jitsi/jitsi-media-transform/pull/227, in hopes that the latter's PR tests pass.

Fail to project VP8 packets without picture IDs

---

src/main/java/org/jitsi/videobridge/Endpoint.java

Setting the log level to FINE on Endpoint is basically filled with this log, currently.

Move SR relay log to trace

---

src/main/java/org/jitsi/videobridge/octo/OctoRelay.java

The Octo socket is non-blocking, so send() will block if the buffer isn't big enough.

Increase size of Octo socket send buffer.

---

src/main/java/org/jitsi/videobridge/Conference.java
src/main/java/org/jitsi/videobridge/ConferenceSpeechActivity.java
src/main/java/org/jitsi/videobridge/cc/BitrateController.java

`BitrateController` needs to be told any time the order of active speakers changes (and have the new, correct order) for last-n to work correctly.  This issue did not affect non-last-n calls, as a `dominantSpeakerChanged` message would be sent to the client which would respond with a `SelectedEndpointMessage`.  Since selected endpoints are always given priority, that client would always be prioritized.  With last-n enabled, though, the `BitrateController` must have an accurate, up-to-date ordering of active endpoints so that the proper ones make it into last-n.
Note: in debugging this, we found the flow around updating the interested parties when active-speaker-list changes happen (which can be driven by a few things) feels pretty messy and would be worth revisiting; so this fix feels …

Update the BitrateController any time the active speaker changes

---

pom.xml
src/main/java/org/jitsi/videobridge/DtlsTransport.java
src/main/java/org/jitsi/videobridge/octo/OctoTentacle.java

This makes sure we don't treat internal packet queueing times as network congestion, causing us to reduce sending bandwidth.
Depends on https://github.com/jitsi/jitsi-media-transform/pull/245 .

Record tcc timestamps when packets are sent

---

doc/rest-colibri.md
doc/statistics.md

According to https://community.jitsi.org/t/proposed-videobridge-stats-removal/20431 the system-level statistics cpu_usage, total_memory and used_memory have been removed. It took me a while to find this news post and stop wondering why these three values aren't reported by my instance. In order to prevent confusion, these three values should also be removed from the docs.

Remove system-level statistics from README

---

pom.xml
src/main/kotlin/org/jitsi/videobridge/ice/IceConfig.kt
src/main/kotlin/org/jitsi/videobridge/transport/ice/IceTransport.kt
src/main/resources/reference.conf

Depends on https://github.com/jitsi/ice4j/pull/197.

Add config option for ICE nomination strategy.

---

src/main/java/org/jitsi/videobridge/rest/ssi/SSIResourceHandler.java

Closeable interface or its super-interface, AutoCloseable, needs to be closed after use.

Fix for Resource

---

pom.xml
src/main/java/org/jitsi/videobridge/cc/AdaptiveTrackProjection.java
src/main/java/org/jitsi/videobridge/cc/GenericAdaptiveTrackProjectionContext.java
src/main/java/org/jitsi/videobridge/cc/vp8/VP8AdaptiveTrackProjectionContext.java
src/main/java/org/jitsi/videobridge/cc/vp8/VP8Frame.java
src/main/java/org/jitsi/videobridge/cc/vp8/VP8FrameProjection.java
src/main/java/org/jitsi/videobridge/cc/vp8/VP8QualityFilter.java

This works around a FF 75 bug https://bugzilla.mozilla.org/show_bug.cgi?id=1628851 .
Also improve some logging.

Allow VP8 layers without temporal scalability

---

src/main/java/org/jitsi/videobridge/Videobridge.java
src/main/java/org/jitsi/videobridge/rest/JSONDeserializer.java

This PR replaces the usage of the deprecated  `StringUtils.isNullorEmpty` with plain java calls.
Currently, there are a few more deprecated references in the codebase, but idk what the replacement for those instances is.
If someone can point me in the right direction I'll create PRs for those as well.
```
[WARNING] /jitsi-videobridge/src/main/java/org/jitsi/videobridge/octo/OctoPacket.java:[146,29] DATA in org.jitsi.utils.MediaType has been deprecated
[WARNING] /jitsi-videobridge/src/main/java/org/jitsi/videobridge/octo/OctoRelay.java:[409,26] DATA in org.jitsi.utils.MediaType has been deprecated
[WARNING] /jitsi-videobridge/src/main/java/org/jitsi/videobridge/stats/VideobridgeStatistics.java:[112,25] RTP_LOSS in org.jitsi.xmpp.extensions.colibri.ColibriStatsExtension has been deprecated …
```

Replace deprecated usage of Stringutils with plain java calls

---

src/main/kotlin/org/jitsi/videobridge/transport/ice/IceTransport.kt

Sending here increased the likelihood that we'd send on a socket that was closed, since we free the `IceAgent` in `IceTransport#stop`.

Don't send in IceTransport if it's not running

---

src/main/java/org/jitsi/videobridge/AbstractEndpointMessageTransport.java
src/main/java/org/jitsi/videobridge/Endpoint.java
src/main/java/org/jitsi/videobridge/EndpointMessageTransport.java
src/main/java/org/jitsi/videobridge/octo/OctoEndpointMessageTransport.java
src/main/java/org/jitsi/videobridge/websocket/ColibriWebSocket.java
src/main/java/org/jitsi/videobridge/websocket/ColibriWebSocketServlet.java

This decouples websocket code from the endpoint, and instead defines an event handler in `ColibriWebSocket` which can be implemented.  It also skips passing websocket messages through the Endpoint and sends them directly to the endpoint message transport (the code in endpoint was just passthrough logic anyway).  
This is some refactoring I bumped into when doing work to make Octo endpoints more similar to local endpoints.

Msg transport handler interfaces

---

src/main/java/org/jitsi/videobridge/AbstractEndpoint.java
src/main/java/org/jitsi/videobridge/Conference.java
src/main/java/org/jitsi/videobridge/Endpoint.java
src/main/java/org/jitsi/videobridge/Videobridge.java
src/main/java/org/jitsi/videobridge/octo/ConfOctoTransport.java
src/main/java/org/jitsi/videobridge/octo/OctoEndpoints.java
src/main/java/org/jitsi/videobridge/octo/OctoTentacle.java
src/main/java/org/jitsi/videobridge/octo/OctoTransceiver.java
src/main/java/org/jitsi/videobridge/shim/ChannelShim.java
src/main/java/org/jitsi/videobridge/shim/ConferenceShim.java
src/main/kotlin/org/jitsi/videobridge/octo/OctoEndpoint.kt
src/main/kotlin/org/jitsi/videobridge/octo/OctoRelayService.kt
src/main/kotlin/org/jitsi/videobridge/octo/config/OctoRtpSender.kt
src/main/kotlin/org/jitsi/videobridge/transport/octo/BridgeOctoTransport.kt
src/main/kotlin/org/jitsi/videobridge/transport/octo/OctoUtils.kt
src/main/resources/reference.conf

This is another step in making Octo/remote endpoints act more like local endpoints.  This change moves from a single `OctoTransceiver` instance per conference to one per `OctoEndpoint`, and the `OctoTentacle` demuxes incoming Octo packets to their appropriate `OctoEndpoint` for processing (note that a conference-level `OctoTransceiver` does still exist to process incoming Octo packets which originated from a remote bridge and have no source endpoint ID set).
This means that we no longer have a single incoming Octo packet queue per conference, but instead individual queues per remote endpoint, just like local endpoints.

Move octo pipelines to individual OctoEndpoint instances

---

src/main/kotlin/org/jitsi/videobridge/octo/OctoEndpoint.kt

not doing this was causing leftover endpoints to 'pile up' in the
conference

call super.expire in OctoEndpoint#expire

---

src/main/java/org/jitsi/videobridge/Conference.java
src/main/java/org/jitsi/videobridge/Endpoint.java
src/main/java/org/jitsi/videobridge/health/Health.java
src/main/java/org/jitsi/videobridge/shim/ConferenceShim.java

As long as `Endpoint` no longer generate `IOException` it could be removed, what do you think?

Drop IOException from Endpoint constructor signature.

---

debian/postinst

Fixes #1239.
Fixes #1254.
Resolves #1264.

debian/postinst: skip comments when editing config

---

src/main/java/org/jitsi/videobridge/Conference.java
src/main/java/org/jitsi/videobridge/Videobridge.java
src/main/java/org/jitsi/videobridge/eventadmin/callstats/ConferencePeriodicRunnable.java
src/main/java/org/jitsi/videobridge/shim/ConferenceShim.java

Pass a`String` instead of a `Localpart` for the conference name.  This is something I came across when doing JVB API investigation, since we won't have a `Localpart` in the future.

Some small cleanup - mainly removing Localpart from Conference.java

---

jvb-api/jvb-api-client/pom.xml
jvb-api/jvb-api-common/pom.xml
jvb-api/jvb-api-server/pom.xml
jvb-api/pom.xml

I think this must have not gotten caught due to some cached versions (from before the pom hierarchy change) as part of https://github.com/jitsi/jitsi-videobridge/pull/1268

make the version strings used consistent across all poms

---

resources/build_deb_package.sh

mvn dependency:resolve expects all packages to be in a remote repo, but
with the jvb api we have the packages locally.  since this call was only
made to make sure everything was downloaded, use mvn package instead
which doesn't expect everything to be remote.

don't use mvn dependency:resolve to cache deps

---

debian/rules

The packages need to be installed locally (it seems) for `mvn dependency:copy-dependencies` in the debian package build to work correctly.

install jars to local repo

---

src/main/java/org/jitsi/videobridge/cc/BitrateController.java
src/test/java/org/jitsi/videobridge/cc/EndpointMultiRankerTest.java

@paweldomas discovered this issue where the prioritization order that the EndpointMultiRanker implements is inversed, leading to the wrong endpoints being allocated bandwidth first. The comments in the patch provide further information.

fix: The on-stage participants becomes suspended when last-n equals 1.

---

doc/rest-colibri.md

Link "using_statistics.md#configuration" is not valid anymore, it is replaced by https://github.com/jitsi/jitsi-videobridge/blob/master/doc/rest.md#introduction

Fixing link for setting up stats

---

src/main/java/org/jitsi/videobridge/Conference.java
src/main/java/org/jitsi/videobridge/Videobridge.java
src/main/java/org/jitsi/videobridge/health/Health.java
src/main/java/org/jitsi/videobridge/octo/ConfOctoTransport.java
src/main/java/org/jitsi/videobridge/octo/OctoPacket.java
src/main/java/org/jitsi/videobridge/shim/ConferenceShim.java
src/main/java/org/jitsi/videobridge/shim/VideobridgeShim.java
src/main/kotlin/org/jitsi/videobridge/octo/OctoRelayService.kt
src/main/kotlin/org/jitsi/videobridge/transport/octo/BridgeOctoTransport.kt
src/test/kotlin/org/jitsi/videobridge/octo/OctoPacketTest.kt

This is a draft, because we need to have jicofo `>= b848a9fa19` running on meet.jit.si before merging.

Octo header and GID update

---

src/main/java/org/jitsi/videobridge/EndpointMessageBuilder.java

Adjusts the colibri class name according to https://github.com/jitsi/lib-jitsi-meet/pull/1227/commits/d0b19451e8cf6ed1f00b882387afa28efe3d502f

ref: Make a message name shorter as per @bgrozev's suggestion

---

pom.xml
src/main/java/org/jitsi/videobridge/Conference.java
src/main/java/org/jitsi/videobridge/ConferenceSpeechActivity.java
src/main/java/org/jitsi/videobridge/Endpoint.java
src/main/java/org/jitsi/videobridge/cc/BitrateController.java
src/main/java/org/jitsi/videobridge/octo/OctoTransceiver.java
src/main/java/org/jitsi/videobridge/rest/root/colibri/conferences/Conferences.java
src/main/kotlin/org/jitsi/videobridge/octo/OctoEndpoint.kt
src/main/kotlin/org/jitsi/videobridge/octo/config/OctoRtpReceiver.kt

When ordering the endpoints to forward, order not only by speech activity, but also whether endpoints are sending video (those sending video are put on the top of the list).

Order last-n endpoints by video availability.

---

debian/jitsi-videobridge2.service

When the jvb process exits abnormally (e.g. due to a oom condition),
systemd will restart the process.
fixes #1353

feat(systemd): restart jvb service automatically

---

jvb/pom.xml
pom.xml

From what I can tell, these deps can be safely removed.  Some of them are no longer used at all, and some are still in the dependency tree but not used directly by JVB.

Remove unused deps

---

jvb/src/main/java/org/jitsi/videobridge/rest/RESTBundleActivator.java
jvb/src/main/kotlin/org/jitsi/videobridge/RestBundleActivatorConfig.kt
jvb/src/main/resources/reference.conf

I bumped into this when updating AbstractJettyBundleActivator to new config.  RESTBundleActivator was still using an old config, so this PR removes that usage.

port rest api to new config

---

jvb/src/main/java/org/jitsi/videobridge/rest/RESTBundleActivator.java
jvb/src/main/java/org/jitsi/videobridge/websocket/WebSocketBundleActivator.java
jvb/src/main/resources/reference.conf

This PR changes the location of the http server configuration to make it more explicit.  It also restores a the previous default behavior of disabling the public http server by default (this was broken unintentionally in https://github.com/jitsi/jitsi-videobridge/pull/1375).
No other changes are needed here as there was no default config before.

Rework http server config

---

jvb/src/main/java/org/jitsi/videobridge/Main.java
jvb/src/main/java/org/jitsi/videobridge/octo/ConfOctoTransport.java
jvb/src/main/java/org/jitsi/videobridge/osgi/BundleConfig.java
jvb/src/main/java/org/jitsi/videobridge/stats/VideobridgeStatistics.java
jvb/src/main/kotlin/org/jitsi/videobridge/octo/OctoRelayService.kt
jvb/src/main/kotlin/org/jitsi/videobridge/octo/OctoRelayServiceProvider.kt
jvb/src/test/kotlin/org/jitsi/videobridge/ConferenceTest.kt

There wasn't much preventing `OctoRelayService` from becoming a 'regular' class instead of an OSGi service, so this PR moves it away from an OSGi service.
Although I didn't do it here, it wouldn't be too bad to plumb in an `OctoRelayServiceSupplier` instance to the classes that need it which would prevent them accessing a global singleton.  Neither of those classes currently have tests so I didn't bother doing that here.

change octorelayservice to not be an osgi service

---

pom.xml

fix: Prevents a java.util.concurrent.RejectedExecutionException

chore: Updates jicoco to lates.

---

jvb/src/main/java/org/jitsi/videobridge/cc/BitrateController.java
jvb/src/main/kotlin/org/jitsi/videobridge/cc/config/BitrateControllerConfig.kt
jvb/src/main/resources/reference.conf

This PR adds a configurable interval at which we'll force a call to `BitrateController#update` if it has not run.  
I'll note that the scheduling of `update` tasks is not foolproof with regards to potential duplicates: to address this I think we'd probably implement a _minimum_ time between updates as well.  I can add that if we think it would be worthwhile, but we don't currently gate calls to `update` and this didn't seem like it would add a significant increase.

Enforce an interval at which BitrateController#update runs

---

jvb/src/main/java/org/jitsi/videobridge/xmpp/MediaSourceFactory.java
jvb/src/test/java/org/jitsi/videobridge/xmpp/MediaSourceFactoryTest.java

`MediaSourceFactoryTest` has been flaky.  I suspect this may stem from our use of the `Whitebox` lib to modify a static member.  It turns out we don't need this static member, so this PR removes it and adapts the tests (as well as some other cleanup).

Attempt to fix MediaSourceFactoryTest flakiness

---

jvb/src/main/java/org/jitsi/videobridge/cc/BitrateController.java
jvb/src/main/kotlin/org/jitsi/videobridge/JvbLastN.kt
jvb/src/main/resources/reference.conf
jvb/src/test/kotlin/org/jitsi/videobridge/JvbLastNKtTest.kt

This is another step in survival-last-n: it implements a last-n setting on the JVB level which will be applied to all endpoints.  Endpoints do not just take this JVB value, but instead the minimum of any last-n setting they have at the endpoint level and this JVB setting.  Soon, the load manager will leverage this field to reduce load on the bridge when needed.

JVB-wide last-n value

---

jvb/src/main/java/org/jitsi/videobridge/Conference.java

This PR fixes a couple things from the ep connection status monitor refactoring done in https://github.com/jitsi/jitsi-videobridge/pull/1384:
1. Correctly stop the monitor when a conference expires.  This was not an issue before as we had a single, global ep connection status monitor
1. Don't perform ep connection status monitoring for health check conferences.  The old code didn't ignore health check conferences, but it's a waste to monitor endpoint connection status for them.
I also cleaned up a couple low-hanging-fruit IDE warnings.

Ep connection monitor fixes

---

debian/install

Fixes error `Exception in thread "Global IO pool-3" java.lang.NoClassDefFoundError: Could not initialize class com.fasterxml.jackson.databind.deser.std.JdkDeserializers` that is due to dependencies of different versions.

fix: Fixes #1412 NoClassDefFoundError JdkDeserializers

---

jvb/src/main/kotlin/org/jitsi/videobridge/JettyHelpers.kt

I was setting the port inside the `HttpConfiguration` but not on the `ServerConnector` for the secure Jetty setup, which was resulting in the secure Jetty server starting on a random port.
It turns out we don't seem to need the custom `HttpConfiguration` and it was confusing to set the port in a couple places, so I removed that and we now just use a default `HttpConnectionFactory` (which instantiates a default `HttpConfiguration`)

set the port on the http connector

---

jvb/src/main/kotlin/org/jitsi/videobridge/octo/OctoRelayService.kt

`OctoRelayService` currently has an awkward flow where `start` can swallow an exception and be in a state where it was enabled, and therefore exists, but hasn't set its `udpTransport` and `bridgeOctoTransport` members, which causes an issue when calling `OctoRelayService#getStats`.
This fix changes `getStats` to handle the cases where those members are null, but the plan in the future will be to avoid this awkward state of `OctoRelayService` altogether (likely by having it fail to be created at all).

handle octo relay service failing to start in getStats

---

debian/postinst

The intent here is to generate an empty `jvb.conf` if one doesn't exist, and pass this config file (via `-Dconfig.file`) to the bridge when starting up so that debian installs can support the new configuration.
I didn't go so far as to migrate any configurations put in `sip-communicator.properties` into the new config, as the logic in this script is already pretty complex (already supports migrating from an old, _old_ config file). Maybe there's some code that can be cleaned up/removed there for the older cases?

add support for new config file in debian installs

---

jvb/src/main/java/org/jitsi/videobridge/cc/BitrateController.java

fix: This PR fixes an issue that was causing dramatic oversending for participants with low bandwidth in tile view.  Before this change, when the `enableOnstageVideoSuspend` config parameter was false (which is the default setting) we would end up forwarding the lowest quality layer for _all_ participants when a receiver was in tile view, even if their bandwidth couldn't handle it.  `enableOnstageVideoSuspend` was intended to prevent the suspension of a screenshare stream so that receivers would always receiver screenshare, but the way it was implemented ended up resulting in this issue due to changes in https://github.com/jitsi/jitsi-videobridge/pull/1250 which altered the definition of what ended up being considered as an 'on stage' participant.  The fix allows only forcing the …

only disable complete suspension for highest priority endpoint when forwarding

---

jvb/src/main/java/org/jitsi/videobridge/Main.java
jvb/src/main/java/org/jitsi/videobridge/stats/VideobridgeStatistics.java

This PR passes the needed dependencies to the `VideobridgeStatistics` constructor instead of it using the singletons to grab things.  See https://github.com/jitsi/jitsi-videobridge/issues/1444

Pass dependencies into VideobridgeStatistics rather than using singletons

---

jvb/src/main/kotlin/org/jitsi/videobridge/octo/OctoRelayService.kt
jvb/src/main/kotlin/org/jitsi/videobridge/octo/OctoRelayServiceProvider.kt

There were some awkward flows in `OctoRelayService` where we didn't initialize members until `start`, so they had to be nullable.  This moves the initialization to the constructor so we can avoid that.

OctoRelayService cleanup

---

jvb/src/main/java/org/jitsi/videobridge/cc/BandwidthProbing.java
jvb/src/main/kotlin/org/jitsi/videobridge/octo/config/OctoRtpSender.kt
pom.xml

Should fix observed packet losses.

Fix: don't over-send bandwidth probing, and send bandwidth probing even when no sources can be sent.

---

jvb/src/main/java/org/jitsi/videobridge/rest/root/Application.java
jvb/src/main/java/org/jitsi/videobridge/rest/root/colibri/conferences/Conferences.java
jvb/src/main/java/org/jitsi/videobridge/rest/root/colibri/mucclient/MucClient.java
jvb/src/main/java/org/jitsi/videobridge/rest/root/colibri/shutdown/Shutdown.java
jvb/src/main/java/org/jitsi/videobridge/rest/root/colibri/stats/Stats.java
jvb/src/main/java/org/jitsi/videobridge/rest/root/debug/Debug.java
jvb/src/main/kotlin/org/jitsi/videobridge/JettyHelpers.kt
jvb/src/main/kotlin/org/jitsi/videobridge/Main.kt
jvb/src/main/kotlin/org/jitsi/videobridge/rest/binders/ServiceBinder.kt
jvb/src/test/java/org/jitsi/videobridge/rest/root/colibri/stats/StatsTest.java
jvb/src/test/java/org/jitsi/videobridge/rest/root/debug/DebugTest.java
jvb/src/test/kotlin/org/jitsi/videobridge/rest/root/colibri/mucclient/MucClientTest.kt

This is more work on https://github.com/jitsi/jitsi-videobridge/issues/1444, and passes instances down from Main instead of having other classes grab them via singletons.

Refactor ServiceBinder to take services instances instead of using global singletons

---

jvb/src/main/java/org/jitsi/videobridge/xmpp/MediaSourceFactory.java
jvb/src/test/java/org/jitsi/videobridge/xmpp/MediaSourceFactoryTest.java

Previously, we assumed that when simulcast was enabled, 3 temporal layers would
be present in each stream and if simulcast wasn't enabled, there would be only
1 temporal layer per stream, but we found that screenshare started sending 2
temporal layers, and we'd therefore start dropping layer 1 packets since we didn't
recognize them.  The truth is we have no way of _knowing_ how many temporal layers
there are going to be (as it's not signaled) unless we dynamically read the layers
as the packets come in (which we may want to do in the future)--but for now we'll
over-estimate how many layers there are per stream to avoid dropping packets for a
layer we don't recognize.  Since there are already situations where chrome sends fewer
temporal layers than we assume, this should be safe.

fix: always assume 3 temporal layers

---

jvb/src/main/java/org/jitsi/videobridge/Conference.java

This null-check is present in constructor but missing in getDebugState

Fix NullPointerException if conferenceName is not defined.

---

jvb/src/main/java/org/jitsi/videobridge/EndpointMessageTransport.java

In our project we use bare JVB as a library and for some reason we have custom implementation of AbstractEndpoint for communication with regular Endpoints in a conference. At the moment EndpointMessages are not sent to that "custom" EP since it is not Endpoint nor OctoEndpoint.
I would like to ask you to merge this small change to allow messaging with any kind of AbstractEndpoint.

Allow sending EndpointMessage to the custom Endpoints.

---

jvb/src/main/java/org/jitsi/videobridge/AbstractEndpoint.java
jvb/src/main/java/org/jitsi/videobridge/Conference.java
jvb/src/main/java/org/jitsi/videobridge/Endpoint.java

This is the start of some work to get rid of all the dependencies on `Conference` we have in `AbstractEndpoint` and its subclasses.  It uses the `EventEmitter` class introduced in https://github.com/jitsi/jitsi-videobridge/pull/1473, so that PR will need to be merged first.

Fire events from Endpoint

---

jvb/src/main/java/org/jitsi/videobridge/Conference.java
jvb/src/main/java/org/jitsi/videobridge/Endpoint.java
jvb/src/main/java/org/jitsi/videobridge/Videobridge.java
jvb/src/main/java/org/jitsi/videobridge/stats/VideobridgeStatistics.java
jvb/src/main/kotlin/org/jitsi/videobridge/health/JvbHealthChecker.kt
jvb/src/test/kotlin/org/jitsi/videobridge/ConferenceTest.kt

After discussing with @bgrozev, this aspect of the check was adding very little value and leads to some awkwardness with having to deal with these "special" conferences, so removing this logic.  It's possible we'll bring it back in some other form in the future.

Remove conf/ep creation from health checks

---

jvb/src/main/resources/application.conf
jvb/src/main/resources/reference.conf
pom.xml

This, in combination with the linked jicoco-config PR, fixes JVB config overrides of properties it uses (previously it worked in some envs coincidentally based on classpath loading order, but did always fail to properly override ICE4j config when deploying a fat jar).
Depends on https://github.com/jitsi/jicoco/pull/118

move ice4j overrides to application.conf

---

jvb/src/main/java/org/jitsi/videobridge/Endpoint.java
jvb/src/main/java/org/jitsi/videobridge/cc/BitrateController.java
jvb/src/main/kotlin/org/jitsi/videobridge/message/BridgeChannelMessage.kt
jvb/src/test/kotlin/org/jitsi/videobridge/message/BridgeChannelMessageTest.kt

The jitsi-meet client no longer relies on the "endpointsEnteringLastN" and "conferenceEndpoints" fields, and they carry no useful information.

ref: Remove unused fields from ForwardedEndpointsMessage.

---

jvb/src/main/java/org/jitsi/videobridge/rest/root/Application.java
jvb/src/main/java/org/jitsi/videobridge/rest/root/colibri/stats/Stats.java
jvb/src/main/kotlin/org/jitsi/videobridge/Main.kt
jvb/src/main/kotlin/org/jitsi/videobridge/rest/binders/ServiceBinder.kt

Stats can be disabled, and this was causing an issue when crossing a Java -> Kotlin boundary as Kotlin was expecting a non-null type, but this was from java so it didn't get enforced (hence why we didn't see this at compile time).  Jersey/hk2 didn't play too nicely with injecting a nullable type, so I had to play with that a bit and only conditionally inject in the non-null case and mark the injection as `Optional`.  
Fixes https://github.com/jitsi/jitsi-videobridge/issues/1503

fix: Avoid IllegalStateException when StatsCollector is disabled

---

pom.xml

Built with latest jetty, jersey, and typesafe config libs.

Update: Use latest jicoco.

---

jvb/src/main/java/org/jitsi/videobridge/Endpoint.java
jvb/src/main/java/org/jitsi/videobridge/cc/BitrateController.java
jvb/src/main/java/org/jitsi/videobridge/stats/VideobridgeStatistics.java
jvb/src/main/kotlin/org/jitsi/videobridge/cc/OversendingTimeTracker.kt
jvb/src/test/kotlin/org/jitsi/videobridge/cc/OversendingTimeTrackerTest.kt

This PR adds two forms of an 'oversending' stat:
It adds a Videobridge stat which counts the total number of endpoints we're currently "oversending" to, as well as a debug state that shows the total oversending time for an endpoint.
Note that this definition of "oversending" is "knowingly oversending" due to `enableOnstateVideoSuspension` being false (so we always force 1 on-stage video stream).
I'm not ecstatic about the implementation of the videobridge stat--I find it odd that `VideobridgeStatistics.java` has to knowingly request all the stats it wants--but I think we already had some plans to clean that up so I did what seemed consistent with the others.

Add oversending stat

---

jvb/src/main/java/org/jitsi/videobridge/rest/root/debug/Debug.java
jvb/src/main/java/org/jitsi/videobridge/util/ByteBufferPool.java
jvb/src/test/java/org/jitsi/videobridge/rest/root/debug/DebugTest.java

This PR *changes* the REST endpoints for accessing debug feature stats and changing their states (enabled or disabled). Redirects are added for the accessing endpoints, but not the changing ones (redirects don't seem to play nicely with preserving the HTTP methods).
We used to have:
```
POST /enable/{feature} - turns jvb {feature} on
POST /disable/{feature} - turns jvb {feature} off
POST /{confId}/{epId}/{state}/{feature} - turns endpoint {feature} on or off for a specific endpoint (currently only pcap)
GET  /stats/{feature} - gets the data for a jvb feature (redirect provided)
```
After this change, we now have:
```
POST /features/jvb/{feature}/{enabled} - set the state of jvb feature {feature} (where {enabled} is `true` or `false`)
POST …
```

Debug rest changes

---

jvb/src/main/kotlin/org/jitsi/videobridge/load_management/LastNReducer.kt
jvb/src/main/resources/reference.conf

This PR addresses 2 things:
1) Increases the minimum last-n value from 0 to 1.  This is more in line with the fact that we, by default, always allow the on-stage participant be forwarded, so we won't run into any weird conflicts between survival last n and that code
2) Fixes an issue with recovery: before, we'd increase the current last-n value by the configured recovery scale but for small numbers (especially 0...) this can result in the increase being too small to reach the next integer, so the last-n value gets "stuck".  The second commit ensures we always increase the value by at least one when recovering.
I plan to merge the commits here without squashing.

Survival last n fixes

---

jvb/src/main/java/org/jitsi/videobridge/rest/root/debug/Debug.java
jvb/src/main/java/org/jitsi/videobridge/rest/root/debug/DebugFeatures.java
jvb/src/main/java/org/jitsi/videobridge/util/ByteBufferPool.java
jvb/src/main/java/org/jitsi/videobridge/util/PartitionedByteBufferPool.java

This PR implements buffer pool "bookkeeping" as a "debug feature" which can be turned on and off using the existing private rest api.  The "get stats" path does not apply for this feature, as this feature doesn't maintain stats, just logs issues.  We could look at changing that, but I think that should probably be in a different PR anyhow.

Allow enabling/disabling buffer pool bookkeeping via (private) REST API

---

jvb/src/main/java/org/jitsi/videobridge/util/ByteBufferPool.java
jvb/src/main/java/org/jitsi/videobridge/util/PartitionedByteBufferPool.java
jvb/src/main/kotlin/org/jitsi/videobridge/Main.kt

While trying to track down some buffer issues, I found that we were hitting hash collisions using `System.identityHashCode` on buffers as a key in our bookkeeping.  @JonathanLennox found `IdentityHashMap` which uses a combination of `identityHashCode` and equality to compare and that has fared better, so this PR changes the BufferPool bookkeeping structures to use `IdentityHashMap`.
I also found that we can just store an `Exception` of the stacktraces and expand it into a `String` only when needed, which appears to give a performance boost, so this PR changes the tracking to use `Exception` instead of `String`.
We also used to log on every buffer request and return, but that didn't give a complete picture and was very chatty.  I changed it to instead track a timeline per buffer of all …

Change BufferPool bookkeeping

---

jvb/src/main/java/org/jitsi/videobridge/util/ByteBufferPool.java

(Whether via enableStatistics or bookkeepingEnabled)

Only output ByteBufferPool stats when their calculation is enabled.

---

jvb/src/main/kotlin/org/jitsi/videobridge/EndpointConnectionStatusMonitor.kt
jvb/src/test/kotlin/org/jitsi/videobridge/EndpointConnectionStatusMonitorTest.kt

@paweldomas noticed a scenario where, if the first time the `EndpointConnectionStatusMonitor` checked a given endpoint's status and it had no activity at that time, we would notify endpoints that it was inactive but not _track_ it as having been marked as inactive in the bridge, so we'd never send an update when it went active (since the bridge didn't remember it had been marked as inactive).
I still need to look over this a bit more, but so far the unit test seems to confirm the issue and the fix.  Putting it up so @paweldomas can take a look.

Fix scenario where endpoint connection status can get stuck on 'inactive'

---

jvb/src/main/java/org/jitsi/videobridge/Endpoint.java
jvb/src/main/kotlin/org/jitsi/videobridge/octo/config/OctoRtpReceiver.kt
pom.xml

This change adds the ability for a moderator to deactivate the camera of other participants. The implementation uses the same approach that was implemented to mute audio of other participants.
This feature consists of multiple PRs:
- https://github.com/jitsi/jitsi-media-transform/pull/329
- https://github.com/jitsi/jitsi-videobridge/pull/1570
- https://github.com/jitsi/jitsi-xmpp-extensions/pull/37
- https://github.com/jitsi/jicofo/pull/695
- https://github.com/jitsi/lib-jitsi-meet/pull/1496
- https://github.com/jitsi/jitsi-meet/pull/8630

Added mute video moderation feature

---

jvb/src/main/kotlin/org/jitsi/videobridge/Main.kt
jvb/src/main/kotlin/org/jitsi/videobridge/xmpp/config/XmppClientConnectionConfig.kt
jvb/src/main/resources/reference.conf

Profiling shows us blowing out the Smack XMPP JID parsing cache in large conference tests -- the default cache size is only 100.  This increases it to something bigger than we're likely to need for JVBs for now.

Set Smack XMPP JID cache size on startup.

---

jvb/src/main/kotlin/org/jitsi/videobridge/message/BridgeChannelMessage.kt

We saw this come up in our load test traces, and from the simple test I wrote it looks like it could be a decent win: Parsing 1000 EndpointMessages went from ~1 second with the old code to ~60ms.

reuse jackson object mapper instance

---

jvb/src/main/java/org/jitsi/videobridge/Conference.java
jvb/src/main/java/org/jitsi/videobridge/Videobridge.java
jvb/src/main/java/org/jitsi/videobridge/shim/VideobridgeShim.java
jvb/src/main/kotlin/org/jitsi/videobridge/xmpp/XmppConnection.kt
pom.xml

This is somewhat awkward for two reasons:
1. We need to maintain the synchronous handling because of [COLIBRI over REST](https://github.com/jitsi/jitsi-videobridge/blob/master/jvb/src/main/java/org/jitsi/videobridge/rest/root/colibri/conferences/Conferences.java#L171)
2. The existance of VideobridgeShim. I think we can just merge the remainder of it in ConferenceShim, but I'd rather not do the change right now.

feat: Handle Colibri requests asynchronously.

---

debian/postinst

(users doubleclick a host name and paste result in the installer)
how to reproduce ? install in a clean instance and add a space before the host name
Result:
https://community.jitsi.org/t/installation-problem-on-ubuntu-20-04-2-lts/94776

handles spaces around hostname

---

jvb/src/main/java/org/jitsi/videobridge/AbstractEndpoint.java
jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/ReceiverConstraintsMap.kt
jvb/src/test/kotlin/org/jitsi/videobridge/cc/allocation/ReceiverConstraintsMapTest.kt

When doing large call testing, we noticed a very hot call path where we figure out what the maximum height of a set of constraints is.  This change keeps track of the max height as constraints are added and removed from the map so we don't have to walk the entire thing to find it.
Note: `AbstractEndpoint#receiverVideoConstraintsChanged` should probably take a some structure which has max values for various constraints, but currently we only look at maxHeight so rather than define that new class now, I changed the function to just take `int maxHeight`.  It won't be difficult to expand that later when we use other constraints.

Improve performance of determining max height of receiver constraints

---

jvb/src/main/java/org/jitsi/videobridge/websocket/ColibriWebSocketServlet.java
jvb/src/main/kotlin/org/jitsi/videobridge/websocket/config/WebsocketServiceConfig.kt
jvb/src/main/resources/reference.conf

It uses a surprisingly large amount of CPU.

Support disabling websocket compression on the bridge channel.

---

jvb/src/main/java/org/jitsi/videobridge/util/PartitionedByteBufferPool.java

The Java 8 documentation says "the concurrent use of the same java.util.Random
instance across threads may encounter contention and consequent poor
performance. Consider instead using ThreadLocalRandom in multithreaded designs."
Indeed, in a profile, PartitionedByteBufferPool.getPartition() was 1% of total JVB time.

Use ThreadLocalRandom.current() in PartitionedByteBufferPool.

---

jvb/src/main/java/org/jitsi/videobridge/cc/allocation/SingleSourceAllocation.java
pom.xml

Use new lighter-weight "RtpLayerDesc#hasZeroBitrate" method to compute noActiveLayers in bandwidth allocation.

Fix: switch up to HD quickly when switching to a layer-suspended source. (Bump JMT.)

---

jvb/src/main/java/org/jitsi/videobridge/Conference.java

(ConferenceShim uses conference.getId() to name its PacketQueue.)

Move ConferenceShim construction after conference.id is set.

---

jvb/src/main/java/org/jitsi/videobridge/AbstractEndpoint.java
jvb/src/main/java/org/jitsi/videobridge/ConferenceSpeechActivity.java
jvb/src/main/java/org/jitsi/videobridge/EndpointMessageTransport.java
jvb/src/main/java/org/jitsi/videobridge/octo/OctoEndpointMessageTransport.java
jvb/src/main/java/org/jitsi/videobridge/octo/OctoTransceiver.java
jvb/src/main/kotlin/org/jitsi/videobridge/Endpoint.kt
jvb/src/main/kotlin/org/jitsi/videobridge/message/BridgeChannelMessage.kt
jvb/src/main/kotlin/org/jitsi/videobridge/util/VideoType.kt
jvb/src/test/kotlin/org/jitsi/videobridge/SpeechActivityTest.kt
jvb/src/test/kotlin/org/jitsi/videobridge/message/BridgeChannelMessageTest.kt

Allow endpoints to signal the type of video steam they have available, or the lack thereof. Use the signaled video type, instead of the bitrate of the incoming stream when prioritizing endpoints for LastN.
Fixes an issue where an endpoint's video being suspended causes the endpoint to be de-prioritized, and thus video is never unsuspended.
This is a draft, because I want to test some more and add more unit tests.

Signal video type (camera, screenshare, none)

---

jvb/src/main/java/org/jitsi/videobridge/shim/ConferenceShim.java
jvb/src/main/java/org/jitsi/videobridge/shim/ContentShim.java

Not found errors, especially those for endpoint channels, can often
happen when request is made for an endpoint that has expired
on the bridge (due to being disconnected for too long).

ref: log not found errors on warning level

---

jvb-api/jvb-api-client/src/test/kotlin/org/jitsi/videobridge/api/util/WebSocketClientTest.kt

This should be less likely to conflict with an existing listener on the testing machine.

Restrict the random port used for WebsocketClientTest to the 49152-65535.

---

doc/octo.md

Since octo is disabled by default (see https://github.com/jitsi/jicofo/pull/712 ) one needs to enable it to get it running.

Octo is now disable by default, need to enable it.

---

pom.xml

Should prevent crashes after JVB uses up all its heap.

Fix: Bump JMT: Expire RtpPacketCache objects after 15 seconds.

---

jvb/src/main/java/org/jitsi/videobridge/cc/allocation/SingleSourceAllocation.java

Don't treat layers with unknown frame rates as being low-framerate.

Fix forwarding of VP9 screenshare

---

resources/graceful_shutdown.sh

We have a known bug where remote participant counts, and thus conferences, can
get stuck in some cases; don't let that block graceful shutdown.

Use local participant count (not conference count) for graceful shutdown.

---

doc/rest-muc-client.md
jvb/src/main/java/org/jitsi/videobridge/rest/root/colibri/mucclient/MucClient.java
jvb/src/main/kotlin/org/jitsi/videobridge/xmpp/XmppConnection.kt
jvb/src/test/kotlin/org/jitsi/videobridge/rest/root/colibri/mucclient/MucClientTest.kt
pom.xml

This allows listing of ids of previously added XMPP clients.
Ref: https://community.jitsi.org/t/list-added-muc-clients-on-videobridge/100268/6?u=shawn
Depends on the following jicoco changes: https://github.com/jitsi/jicoco/pull/148

Add /colibri/muc-client/list endpoint

---

jvb/src/main/resources/reference.conf

this should be a safer default, with less risk of discarding important packets.

change default value of always-route-dominant to true

---

jvb/pom.xml
jvb/src/test/java/org/jitsi/videobridge/xmpp/MediaSourceFactoryTest.java

There were relics of them in MediaSourceFactoryTest, but they weren't actually doing anything anymore.

Remove use of powermock and easymock from the testing framework.

---

jvb-api/jvb-api-client/pom.xml
jvb/pom.xml

This avoids warnings about incompatible kotlin versions due to jackson-module-kotlin.

Add explicit dependencies on kotlin-reflect.

---

jvb/src/main/kotlin/org/jitsi/videobridge/cc/vp9/Vp9AdaptiveSourceProjectionContext.kt
jvb/src/main/kotlin/org/jitsi/videobridge/cc/vp9/Vp9Frame.kt
jvb/src/main/kotlin/org/jitsi/videobridge/cc/vp9/Vp9Picture.kt
jvb/src/main/kotlin/org/jitsi/videobridge/cc/vp9/Vp9PictureMap.kt
jvb/src/main/kotlin/org/jitsi/videobridge/cc/vp9/Vp9QualityFilter.kt
jvb/src/test/kotlin/org/jitsi/videobridge/cc/vp9/Vp9AdaptiveSourceProjectionTest.kt
jvb/src/test/kotlin/org/jitsi/videobridge/cc/vp9/Vp9QualityFilterTest.kt

Otherwise Chrome's decoder can get confused, and decode the video incorrectly.

Preserve VP9 sequence numbers, picId, and tl0picIdx across suspensions

---

jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/SingleSourceAllocation.kt
jvb/src/main/kotlin/org/jitsi/videobridge/util/VideoType.kt
jvb/src/test/kotlin/org/jitsi/videobridge/message/BridgeChannelMessageTest.kt

This allows the client to signal deskttop_high_fps, but treats it like regular screensharing

feat: Support signaling forr high fps screensharring.

---

jvb/src/main/java/org/jitsi/videobridge/cc/allocation/BandwidthAllocator.java
jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/BandwidthAllocation.kt
jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/SingleSourceAllocation.kt

In anticipation of using rtcstats for debugging quality related issues, I'm adding the ideal/target bitrates in the debug JSON (rtcstats pulls these).

Improves debuggability of bitrate allocations.

---

pom.xml

* Chunk RR packets to have at most 31 report blocks each.
* Generate multiple compound RTCP packets if necessary to fit in MTU.

Bump JMT and RTP: Fixes to avoid generating overly-large RTCP packets.

---

resources/collect-dump-logs.sh

This seems to be necessary with JVM 11, at least in our environment?

When dumping, run jstack and jmap as root, not the jvb user.

---

pom.xml

Work around bug in jxmpp 1.0.1 parsing a JID localpart containing an @ character.

Fix: bump jitsi-xmpp-extensions.

---

jvb/src/main/kotlin/org/jitsi/videobridge/transport/ice/IceTransport.kt

Firefox can't handle ICE candidates where raddr or rport are missing. So we just use raddr=0.0.0.0 and rport=0 instead of dropping these values from the ICE candidate.

fix: use dummy values for raddr and rport instead of dropping them.

---

jvb/src/main/java/org/jitsi/videobridge/stats/MucStatsTransport.java
jvb/src/main/java/org/jitsi/videobridge/stats/Statistics.java
jvb/src/main/kotlin/org/jitsi/videobridge/xmpp/config/XmppClientConnectionConfig.kt
jvb/src/main/resources/reference.conf

Filter is disabled by default.
If enabled, the default whitelist is the set of statistics currently in use.

Add configurable filter for statistics sent to MUC.

---

pom.xml

Notably, this transitively pulls in log4j 2.15.0.

Bump jitsi-stats.

---

jvb/src/main/java/org/jitsi/videobridge/cc/allocation/BandwidthAllocator.java
jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/Layers.kt
jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/SingleSourceAllocation2.kt

Extract Layers data structures into a separate file.
Creates SingleSourceAllocation2.kt which is to be used
by the multi-stream support flow. Eventually this will
be merged later once all changes are identified and
should we still agree it makes sense to merge (as opposed
to keeping separate and deleting old classes once deprecated).
Branches off the multi stream feature flag for the allocation
algorithm in the BandwidthAllocator.java.

feat: allocate multiple streams per endpoint

---

jvb/src/main/java/org/jitsi/videobridge/AbstractEndpoint.java
jvb/src/main/java/org/jitsi/videobridge/Conference.java
jvb/src/main/java/org/jitsi/videobridge/Videobridge.java
jvb/src/main/java/org/jitsi/videobridge/rest/root/colibri/conferences/Conferences.java
jvb/src/main/java/org/jitsi/videobridge/shim/ChannelShim.java
jvb/src/main/java/org/jitsi/videobridge/shim/ColibriUtil.java
jvb/src/main/java/org/jitsi/videobridge/shim/ConferenceShim.java
jvb/src/main/java/org/jitsi/videobridge/shim/ContentShim.java
jvb/src/main/java/org/jitsi/videobridge/shim/EndpointShim.kt
jvb/src/main/java/org/jitsi/videobridge/stats/VideobridgeStatistics.java
jvb/src/main/kotlin/org/jitsi/videobridge/Endpoint.kt

Move more of the quirky colibri1 logic to the shim layer.
- ref: Move Endpoint.channelShims to EndpointShim.
- ref: Move local SSRC generation from the shim to Conference.
- ref: Inline recreateMediaSources (move logic to the shim).
- ref: Move the colibri queue from ConferenceShim to Conference.
- ref: Do not use the shim to count video channels.

Refactor colibri shims

---

jvb/src/main/kotlin/org/jitsi/videobridge/Endpoint.kt

It got lost in a refactor in 2020.

Hook bridge jitter stats up again.

---

doc/statistics.md
jvb/src/main/java/org/jitsi/videobridge/rest/root/debug/Debug.java
jvb/src/main/java/org/jitsi/videobridge/rest/root/debug/DebugFeatures.java
jvb/src/main/java/org/jitsi/videobridge/stats/VideobridgeStatistics.java

Expose it through an HTTP API instead.
Bucket stats were not encoded as intended in presence message.
Also, bucket stats JSON encoding was an issue, see #1714.

Remove tossed-packets-energy from jvb statistics.

---

pom.xml

Also: Move some frequently-reloaded config items to companion objects.

Fix: Bump JMT: Fix RtpEncodingDesc.copy() when there are no layers.

---

jvb/src/main/java/org/jitsi/videobridge/Conference.java
jvb/src/main/java/org/jitsi/videobridge/ConferenceSpeechActivity.java
jvb/src/main/kotlin/org/jitsi/videobridge/Endpoint.kt
pom.xml

Before this change, `isRankedSpeaker` will always return true when there aren't `num-loudest` endpoints speaking at once.

Fix wantsStatsFrom, by fixing isRankedSpeaker.

---

pom.xml

Fixes excessive numbers of warnings in PR testing.

Bump JMT: Don't try to interpret RTX packets marked with shouldDiscard.

---

jvb/src/main/java/org/jitsi/videobridge/stats/VideobridgeStatistics.java

Jicofo will use a safer default instead.

Remove unnecessary early initialization of drain stat.

---

jvb/src/main/kotlin/org/jitsi/videobridge/octo/OctoRelayService.kt
jvb/src/main/kotlin/org/jitsi/videobridge/octo/config/OctoConfig.kt
jvb/src/main/kotlin/org/jitsi/videobridge/relay/RelayedEndpoint.kt
jvb/src/main/resources/reference.conf

Accessing conference.tentacle initializes the octo v1 tentacle. Reported
by @paweldomas.

fix: Read relayId from config directly.

---

jvb/src/main/java/org/jitsi/videobridge/AbstractEndpoint.java
jvb/src/main/java/org/jitsi/videobridge/Conference.java
jvb/src/main/java/org/jitsi/videobridge/EndpointMessageTransport.java
jvb/src/main/java/org/jitsi/videobridge/octo/ConfOctoTransport.java
jvb/src/main/java/org/jitsi/videobridge/octo/OctoEndpointMessageTransport.java
jvb/src/main/java/org/jitsi/videobridge/shim/ConferenceShim.java
jvb/src/main/java/org/jitsi/videobridge/xmpp/MediaSourceFactory.java
jvb/src/main/kotlin/org/jitsi/videobridge/Endpoint.kt
jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/AllocationSettings.kt
jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/BitrateController.kt
jvb/src/main/kotlin/org/jitsi/videobridge/colibri2/Colibri2ConferenceHandler.kt
jvb/src/main/kotlin/org/jitsi/videobridge/message/BridgeChannelMessage.kt
jvb/src/main/kotlin/org/jitsi/videobridge/relay/Relay.kt
jvb/src/main/kotlin/org/jitsi/videobridge/relay/RelayMessageTransport.kt
jvb/src/main/kotlin/org/jitsi/videobridge/relay/RelayedEndpoint.kt
jvb/src/main/kotlin/org/jitsi/videobridge/util/MultiStreamCompatibility.kt
jvb/src/main/resources/reference.conf
jvb/src/test/kotlin/org/jitsi/videobridge/ConferenceTest.kt
jvb/src/test/kotlin/org/jitsi/videobridge/cc/allocation/AllocationSettingsTest.kt
jvb/src/test/kotlin/org/jitsi/videobridge/cc/allocation/BitrateControllerNewTest.kt
jvb/src/test/kotlin/org/jitsi/videobridge/cc/allocation/BitrateControllerPerfTest.kt
jvb/src/test/kotlin/org/jitsi/videobridge/cc/allocation/BitrateControllerTest.kt
pom.xml

Jicofo will forward source name capability for
each Colibri2 Endpoint. In Colibri V1 "use source
names" is always false for now.
Based on the info on whether the client uses source
names or not, will use different signaling messages
for talking to this client. All operations under
the hood are happening on source names.

feat(multi-stream): endpoint ID compatibility

---

jvb/src/main/java/org/jitsi/videobridge/AbstractEndpoint.java
jvb/src/main/kotlin/org/jitsi/videobridge/Endpoint.kt
jvb/src/main/kotlin/org/jitsi/videobridge/relay/RelayedEndpoint.kt

The video types are signaled over data channel while the MediaSourceDesc goes over Colibri. It can happen that
the client sends video type messages before the MediaSourceDesc arrives over Colibri.

fix: cache video type separately

---

jvb/src/main/java/org/jitsi/videobridge/cc/GenericAdaptiveSourceProjectionContext.java

Timestamps were compared to sequence numbers in a couple of places.

Fix timestamp handling in generic projection.

---

jvb/src/main/java/org/jitsi/videobridge/Conference.java
jvb/src/main/java/org/jitsi/videobridge/octo/OctoPacketInfo.java
jvb/src/main/kotlin/org/jitsi/videobridge/colibri2/Colibri2ConferenceHandler.kt
jvb/src/main/kotlin/org/jitsi/videobridge/relay/Relay.kt
jvb/src/main/kotlin/org/jitsi/videobridge/relay/RelayMessageTransport.kt
pom.xml

This allows bridges to be arranged in a tree of full meshes, rather than in a single full-mesh, as currently.  Media packets received from one relay mesh are forwarded to other ones.
Each connection to another relay is identified by a `mesh-id` value, indicating the mesh of relays of which that connection is a part.  It is responsibility of the entity setting up connections between relays (e.g., jicofo) to ensure the topologies are set up correctly.  (This code is not yet written.)
Depends on https://github.com/jitsi/jitsi-xmpp-extensions/pull/70.

Support complex topologies of bridge relays

---

jvb/src/main/resources/reference.conf

When timeout<interval health checks timeout simply because none were
scheduled in the timeout window.

fix: Increase default health check timeout.

---

jvb/src/main/kotlin/org/jitsi/videobridge/colibri2/Colibri2ConferenceHandler.kt

Jicofo handles responses async and may process the second "create
endpoint" response first, resulting in feedback sources not being
signaled to the endpoint.

fix: Include feedback sources with every "create endpoint" response

---

pom.xml

Fix: Don't generate 65535 NACKs when re-receiving the highest sequence number.
Fix: Handle sequence number wrapping in NACK packets.

Bump JMT and RTP.

---

jvb/src/main/kotlin/org/jitsi/videobridge/relay/Relay.kt

Fix: Expire RelayedEndpoint when removing it.

---

jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/RtpReceiver.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/RtpReceiverImpl.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/RtpSender.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/RtpSenderImpl.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/Transceiver.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/rtp/LossListener.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/rtp/TransportCcEngine.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/stats/EndpointConnectionStats.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/transform/node/incoming/TccGeneratorNode.kt
jitsi-media-transform/src/test/kotlin/org/jitsi/nlj/rtp/TransportCcEngineTest.kt
jitsi-media-transform/src/test/kotlin/org/jitsi/nlj/transform/node/incoming/TccGeneratorNodeTest.kt
jvb/src/main/java/org/jitsi/videobridge/stats/callstats/ConferencePeriodicRunnable.java

Previously we would report weird packet loss statistics when we received "weird" TCC packets.
This re-uses the existing processing of loss reports from TransportCcEngine (for outgoing loss) and TccGeneratorNode (for incoming loss) to let us calculate better statistics.

Improve JVB loss statistics

---

jvb/src/main/java/org/jitsi/videobridge/VideobridgeExpireThread.java

As discussed in #1917 decreasing the log level to debug to avoid logs flooding.

Change VideobridgeExpireThread.expire()#L140 log level from info to debug

---

jvb/checkstyle.xml
jvb/src/main/java/org/jitsi/videobridge/AbstractEndpoint.java
jvb/src/main/java/org/jitsi/videobridge/Conference.java
jvb/src/main/java/org/jitsi/videobridge/Videobridge.java
jvb/src/main/java/org/jitsi/videobridge/datachannel/DataChannelStack.java
jvb/src/main/java/org/jitsi/videobridge/rest/root/debug/FeatureState.java
jvb/src/main/java/org/jitsi/videobridge/sctp/SctpManager.java
jvb/src/main/java/org/jitsi/videobridge/util/ByteBufferPool.java
jvb/src/main/java/org/jitsi/videobridge/util/UlimitCheck.java
jvb/src/main/java/org/jitsi/videobridge/websocket/ColibriWebSocket.java
jvb/src/main/java/org/jitsi/videobridge/xmpp/MediaSourceFactory.java

According to [Jitsi's Contributing Guidelines](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-contributing/#formatting), for Java:
> Opening braces MUST be on their own line (especially those beginning a method).
I believe this covers all cases.
To avoid reformatting one-line statements in IDEA, there's a few options under:
Settings > Editor > Code Style > Java > Wrapping and Braces > Keep when reformatting

Add checkstyle rules to match guidelines for opening braces.

---

jvb/src/main/java/org/jitsi/videobridge/Conference.java
jvb/src/main/java/org/jitsi/videobridge/Videobridge.java
jvb/src/main/java/org/jitsi/videobridge/stats/VideobridgeStatistics.java

Port both "failed conferences" stats - `total_failed_conferences` and `total_partially_failed_conferences` - to `CounterMetric` instances, for use with the reworked metrics system. The "total" prefix in the names is omitted for the new `metrics` endpoint (and preserved for the old one) since the Prometheus library automatically adds a `total` suffix.

ref: Port both failed conferences stats to Metrics.

---

jvb/src/main/java/org/jitsi/videobridge/Videobridge.java
jvb/src/main/kotlin/org/jitsi/videobridge/Endpoint.kt
jvb/src/main/kotlin/org/jitsi/videobridge/relay/Relay.kt

I have a couple of concerns regarding metric (and variable) naming.
1. (nitpicking) In this case, I think keeping the "total" prefix reduces ambiguity for Counters with similar Gauge counterparts (e.g., `totalEndpoints` vs. `currentLocalEndpoints`). For standalone Counters we can omit "total".
2. More importantly, the Prometheus library adds a "total" suffix to Counters automatically. However, the JSON (at `/metrics`) , doesn't get this suffix. Worse yet, this behavior can break the `MetricsContainer` (though unlikely):
- Register a CounterMetric named `endpoints` which ends up as `endpoints_total` in the Prometheus registry;
- Register a CounterMetric named `endpoints_total`. This works for `MetricsContainer`, but can't be registered in the Prometheus registry since the library [handles …

Move a few metrics to MetricsContainer.

---

jvb/src/main/java/org/jitsi/videobridge/Conference.java
jvb/src/main/java/org/jitsi/videobridge/Videobridge.java
jvb/src/main/java/org/jitsi/videobridge/stats/VideobridgeStatistics.java
jvb/src/main/kotlin/org/jitsi/videobridge/Endpoint.kt
jvb/src/main/kotlin/org/jitsi/videobridge/relay/Relay.kt

- I assume `dtlsFailedEndpoints` is cumulative, can you confirm?
- `totalDominantSpeakerChanges` is/was a `LongAdder`. Is this for better performance?

Port a few more stats to MetricsContainer.

---

pom.xml

* Append missing _total suffix when registering Counter metrics. (jitsi/jicoco#177)
* Disable all HTTP TRACE requests. (jitsi/jicoco#179)
Fixes #1739

chore: Update jicoco

---

jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/Transceiver.kt
jvb/src/main/kotlin/org/jitsi/videobridge/relay/RelayedEndpoint.kt

This fixes a case where the mediaSources and signaledMediaSources objects could end up sharing a MediaSourceDesc object, leading to encodings not getting properly reset after a VP9 -> VP8 switch.

Fix: Always copy the mediaSources array for signaledMediaSources.

---

jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/transform/node/Node.kt

IntelliJ complains that the `toList()` call is only available from version 16 on. This patch provided by @bgrozev removes the stream usage altogether.

Removed unnecessary streams usage

---

doc/debugging.md

According to https://github.com/jitsi/jitsi-videobridge/blob/master/jvb/src/main/java/org/jitsi/videobridge/rest/root/debug/Debug.java#L352, the documented URL path to the statistic features is wrong: The base is `/debug/stats/`, but not `/debug/features/`

Fix wrong statistic paths

---

jitsi-media-transform/pom.xml
jvb/pom.xml
pom.xml
rtp/pom.xml

A bump to 2.2 was intended with the mono repo changes, but it was only
partially done (a v2.2 tag exists, but pom.xml still lists 2.1).

Bump mvn version to 2.3.

---

jvb/src/main/java/org/jitsi/videobridge/Conference.java

Even if it has no participants - it might be bridging to a visitor relay.

Don't expire a conference that's in multiple meshes.

---

jvb/src/main/java/org/jitsi/videobridge/Videobridge.java

- Remove unnecessary try/catch.
- Actually return health check result.

Fix XMPP health checks

---

jvb/src/main/kotlin/org/jitsi/videobridge/relay/Relay.kt

This fixes inter-relay bridge channels when SCTP datachannels are disabled.

Fix reversed condition adding websockets to transport parameters.

---

jvb/src/main/kotlin/org/jitsi/videobridge/Endpoint.kt
jvb/src/main/kotlin/org/jitsi/videobridge/relay/Relay.kt
jvb/src/main/kotlin/org/jitsi/videobridge/relay/RelayedEndpoint.kt

Fixes finding the AudioSourceDesc when it belongs to a RelayedEndpoint.

fix: Fix broken audio when SSRC rewriting with relays

---

jvb/src/main/kotlin/org/jitsi/videobridge/relay/RelayMessageTransport.kt

The Relay already has its ID in the context resulting in:
relayId=jvb-foo-bar relay-id=jvb-foo-bar

log: Remove redundant log context.

---

jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/BandwidthAllocator.kt

Previously it would use MediaSourceDesc.toString() for the JSON keys, which look like 
```"MediaSourceDesc[name=ec4f16b0-v0 owner=ec4f16b0, videoType=NONE, encodings=primary_ssrc=401428989,secondary_ssrcs={2884778422=RTX},layers=\n    subjective_quality=0,temporal_id=0,spatial_id=-1\n    subjective_quality=1,temporal_id=1,spatial_id=-1\n    subjective_quality=2,temporal_id=2,spatial_id=-1,primary_ssrc=3871341347,secondary_ssrcs={1551935578=RTX},layers=\n    subjective_quality=64,temporal_id=0,spatial_id=-1\n    subjective_quality=65,temporal_id=1,spatial_id=-1\n    subjective_quality=66,temporal_id=2,spatial_id=-1,primary_ssrc=2532834492,secondary_ssrcs={2207419540=RTX},layers=\n    subjective_quality=128,temporal_id=0,spatial_id=-1\n …
```

Use source names as keys to effective constraints debug state.

---

jvb/src/main/resources/application.conf
jvb/src/main/resources/reference.conf
pom.xml

- Bump consent check and inactivity intervals.
- Add missing whitespace in reference.conf.

Increase consent check and inactivity intervals.

---

jvb/src/main/kotlin/org/jitsi/videobridge/relay/RelayMessageTransport.kt

Every time we establish an active WS to another relay we create a new
WebSocketClient instance. This comes with its own QueuedThreadPool with 8 threads
and if we lose the reference without calling stop() it leaks.
When the existing web socket closing arrives before the signaling that
expires the relay, we try do WebSocketClient.stop() and then
doConnect(). The call to stop() can take a while, and if in the meantime
the relay is expired in signaling we end up running doConnect() on
an expired relay. In this case we create a new WebSocketClient, which
is never stopped.
This fix uses a single WebSocketClient instance shared between all
relays, and does not attempt to re-connect if the reason for the
disconnect is RELAY_CLOSED. It re-uses the "webSocket: ColibriWebSocket"
field for sockets …

fix: Fix a leak of WebSocketClients.

---

jvb/src/main/java/org/jitsi/videobridge/Conference.java

- fix: Don't drop audio when routeLoudestOnly is disabled in config.
- fix: Do not drop stats when routeLoudestOnly is disabled.

Fix routing of audio and stats when routeLoudestOnly is disabled

---

pom.xml

chore: Update ice4j kotlin to 1.9

fix: Fix ICE consent checks.

---

jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/transform/node/PcapWriter.kt

Fixed the default value of the parameter filePath for the PcapWriter constructor.
Having a "}" at the end of the file name must have been a typo.

Fixed default file path

---

jvb/src/main/kotlin/org/jitsi/videobridge/health/JvbHealthChecker.kt
jvb/src/main/kotlin/org/jitsi/videobridge/health/config/HealthConfig.kt
jvb/src/main/resources/reference.conf
pom.xml

By default only fail when there is no valid address for ICE. Put the
option to require STUN behind a flag.

feat: Relax the health checks for STUN

---

jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/stats/DelayStats.kt
jvb/src/main/java/org/jitsi/videobridge/EndpointMessageTransport.java
jvb/src/main/java/org/jitsi/videobridge/Videobridge.java
jvb/src/main/kotlin/org/jitsi/videobridge/stats/PacketTransitStats.kt
jvb/src/main/resources/reference.conf
pom.xml

- chore: Update jicoco.
- feat: Implement a Prometheus histogram of  rtp transit time.

feat: Implement a Prometheus histogram of rtp transit time.

---

jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/AllocationSettings.kt
jvb/src/main/resources/reference.conf

feat: Add a config option for default initial last n.

---

debian/control

Needed by pcap4j, but pcap capture is not enabled by default.

Recommend libpcap0.8 for the JVB debian package.

---

jvb/src/main/kotlin/org/jitsi/videobridge/SsrcCache.kt

We have debug logs turned on during PR testing and it blows up the log.

Don't do per-packet debug logging in SsrcCache.

---

jvb/resources/jvb.sh

There was a rewrite of the Java networking stack in Java 13 which made it impossible to concurrently send UDP from multiple threads on the same DatagramSocket.  See https://bugs.openjdk.org/browse/JDK-8303616. This Java option causes Java to use its old DatagramSocket implementation.
Note that unfortunately this workaround does not work in Java 18 and later.

Add a Java option to work around a major performance regression in JDK 17

---

debian/control

Allows for running with Java 17 without any additional install.

Update Java Debian dependencies

---

jvb/pom.xml

This reverts commit 21b42fb2f2b5f3e92d0fdbbe9dce507d0fc2731d.

Revert "Bump jitsi-sctp version: assert if soref() is called on a freed socket. (#2116)"

---

jvb/src/main/java/org/jitsi/videobridge/Conference.java
jvb/src/main/java/org/jitsi/videobridge/Videobridge.java
jvb/src/main/java/org/jitsi/videobridge/rest/root/debug/Debug.java
jvb/src/main/kotlin/org/jitsi/videobridge/Main.kt
jvb/src/main/kotlin/org/jitsi/videobridge/stats/QueueStats.kt
jvb/src/main/kotlin/org/jitsi/videobridge/xmpp/Smack.kt
jvb/src/test/kotlin/org/jitsi/videobridge/VideobridgeTest.kt
pom.xml

- **ref: Do not register xmpp extensions for RAW UDP, we only support ICE.**
- **ref: Remove unused code.**
- **feat: Use JitsiXmppStringprep**
- **doc: Fix javadocs.**
- **ref: Move queue stats out of Videobridge.java.**
- **ref: Move ulimit check out of Videobridge.java.**
- **ref: Move videobridgeExpireThread out of Videobridge.java.**

Use JitsiXmppStringprep, update smack

---

jvb/src/main/java/org/jitsi/videobridge/Conference.java
jvb/src/main/kotlin/org/jitsi/videobridge/AbstractEndpoint.kt
jvb/src/main/kotlin/org/jitsi/videobridge/Endpoint.kt
jvb/src/main/kotlin/org/jitsi/videobridge/SsrcCache.kt

- **ref: Use [] syntax to access map, cleanup.**
- **fix: Remove mappings when an endpoint expires.**

fix: Remove mappings when an endpoint expires.

---

jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/rtp/ParsedVideoPacket.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/rtp/codec/VideoCodecParser.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/rtp/codec/av1/Av1DDPacket.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/rtp/codec/vp8/Vp8Packet.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/rtp/codec/vp9/Vp9Packet.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/transform/node/incoming/VideoParser.kt

If the packets don't have the necessary fields to be routed as their payload type, but they do have an AV1 DD, route them based on the AV1 DD instead.

In some cases, process VP8 or VP9 packets as AV1.

---

jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/rtp/codec/av1/Av1DDPacket.kt
jvb/src/main/kotlin/org/jitsi/videobridge/cc/av1/Av1DDAdaptiveSourceProjectionContext.kt
jvb/src/main/kotlin/org/jitsi/videobridge/cc/av1/Av1DDQualityFilter.kt
rtp/src/main/kotlin/org/jitsi/rtp/rtp/header_extensions/Av1DependencyDescriptorHeaderExtension.kt
rtp/src/test/kotlin/org/jitsi/rtp/rtp/header_extensions/Av1DependencyDescriptorHeaderExtensionTest.kt

The former can be present when the latter is not.

fix(AV1 DD): Separate AV1 DD template's decodeTargetLayers and decodeTargetProtectedBy fields.

---

jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/format/PayloadType.kt
jvb/src/main/kotlin/org/jitsi/videobridge/util/PayloadTypeUtil.kt

The "telephone-event" payload type is currently mapped to OTHER payload type.
This PR introduces TELEPHONE_EVENT payload type and maps "telephone-event" to TELEPHONE_EVENT.
This allows to have more accurate payload type map for PCAP capture functionality and debugging.

Add telephone-event payload type

---

jvb/src/main/java/org/jitsi/videobridge/Conference.java

This is called in the Colibri message processing critical path.

Run lastNEndpointsChanged asynchronously in Conference#endpointSourcesChanged.

---

jitsi-media-transform/pom.xml
jvb/pom.xml
rtp/pom.xml

This change reduces test execution time by about 1 min (30%) on my
machine.
Since the update to kotest 5.9 the following warning gets printed during
tests:
Warning: Kotest autoscan is enabled. This means Kotest will scan the classpath for extensions that are annotated with @AutoScan. To avoid this startup cost, disable autoscan by setting the system property 'kotest.framework.classpath.scanning.autoscan.disable=true'. In 6.0 this value will default to true. For further details see https://kotest.io/docs/next/framework/project-config.html#runtime-detection

ref(test): Disable kotest classpath autoscan

---

jvb/src/main/kotlin/org/jitsi/videobridge/dcsctp/DcSctpTransport.kt

Don't consider streams reset a "Surprising" SCTP callback.

Fix(dcsctp): Allow unlimited sctp retransmissions with dcsctp.

---

jvb/pom.xml
jvb/src/main/kotlin/org/jitsi/videobridge/dcsctp/DcSctpTransport.kt

There were reference cycles through JNI, which the garbage collector can't detect.

Fix(dcsctp): Fix memory leak.

---

pom.xml

- **chore: Update jicoco.**
- **fix(#2184): Revert "chore(deps): Bump jersey.version from 3.0.10 to 3.1.7 (#2145)"**

Fix jetty versions

---

jvb/src/main/kotlin/org/jitsi/videobridge/transport/ice/IceTransport.kt

Otherwise the IceTransport reader job exits.

Catch exceptions processing packets.

---

jvb/src/main/java/org/jitsi/videobridge/Videobridge.java
jvb/src/main/kotlin/org/jitsi/videobridge/Main.kt
jvb/src/main/kotlin/org/jitsi/videobridge/ice/IceConfig.kt
jvb/src/main/kotlin/org/jitsi/videobridge/transport/ice/IceTransport.kt
jvb/src/main/resources/reference.conf

Setting use-component-socket=false has been broken for a long time. We always read/write using the Component's socket:
https://github.com/jitsi/jitsi-videobridge/blob/877b6a2f0fdb98f440e094678116b3b090f59533/jvb/src/main/kotlin/org/jitsi/videobridge/transport/ice/IceTransport.kt#L214
https://github.com/jitsi/jitsi-videobridge/blob/877b6a2f0fdb98f440e094678116b3b090f59533/jvb/src/main/kotlin/org/jitsi/videobridge/transport/ice/IceTransport.kt#L245
- **ref: Move BufferPool setup to Main.**
- **ref: Remove the use-component-socket option.**
- **log: Remove endpoint ID from IceMediaStream name.**

Remove use-component-socket, cleanup

---

jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/MediaSourceDesc.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/RtpLayerDesc.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/rtp/codec/av1/Av1DDRtpLayerDesc.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/rtp/codec/vp9/Vp9Packet.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/rtp/codec/vp9/Vp9Parser.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/rtp/codec/vpx/VpxRtpLayerDesc.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/transform/node/incoming/BitrateCalculator.kt
jvb/src/test/kotlin/org/jitsi/videobridge/cc/allocation/BitrateControllerTest.kt

VP9 flexible mode doesn't announce temporal layers in advance, so add them to the encoding desc as they are encountered.

Support VP9 flexible mode.

---

jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/rtp/TransportCcEngine.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/transform/node/incoming/TccGeneratorNode.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/util/ClockUtils.kt
jitsi-media-transform/src/test/kotlin/org/jitsi/nlj/rtp/TransportCcEngineTest.kt
pom.xml
rtp/src/main/kotlin/org/jitsi/rtp/rtcp/rtcpfb/transport_layer_fb/tcc/RtcpFbTccPacket.kt
rtp/src/test/kotlin/org/jitsi/rtp/rtcp/rtcpfb/transport_layer_fb/tcc/RtcpFbTccPacketTest.kt

Rather than integer microseconds.

Convert TCC packets to use Instant and Duration

---

jvb/src/main/kotlin/org/jitsi/videobridge/Endpoint.kt
jvb/src/main/kotlin/org/jitsi/videobridge/dcsctp/DcSctpTransport.kt
jvb/src/main/kotlin/org/jitsi/videobridge/relay/Relay.kt

(It results in harmless-but-scary warnings in the logs about verification tags being wrong.)

Don't feed SCTP packets to the SCTP stack after it's been closed.

---

jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/RtpSenderImpl.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/transform/node/Node.kt

- **fix: Drop the packet if a preProcessor exists and rejects it.**
- **fix: Also pre-process RTCP packets.**
- **fix: Move the notifyRtcpSent call to the sender pipeline.**
Reported by Philldomd here https://community.jitsi.org/t/version-9646-changes-websocket-removed-and-with-that-rtt-and-jitter-became-0-on-metrics/134871/8

Fix RTT when SSRC rewriting is enabled.

---

jvb/src/main/java/org/jitsi/videobridge/xmpp/MediaSourceFactory.java
jvb/src/main/kotlin/org/jitsi/videobridge/AbstractEndpoint.kt
jvb/src/main/kotlin/org/jitsi/videobridge/Endpoint.kt
jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/BandwidthAllocation.kt

This fixes an issue when a receiver joins a conference and one of the senders has a disabled source. The source was signaled with type NONE, which is not handled correctly by receivers. 
- **fix: Do not signal mappings for disabled sources.**
- **feat: Read initial VideoType from colibri.**
- **feat: Log a warning when video type changes between CAMERA and DESKTOP.**

Do not signal mappings for disabled sources.

---

jvb/src/main/kotlin/org/jitsi/videobridge/metrics/VideobridgeMetrics.kt
jvb/src/main/kotlin/org/jitsi/videobridge/xmpp/XmppConnection.kt
pom.xml

- **feat: Add a metric for XMPP disconnects.**
- **chore: Update jicoco to 1.1-148 (enable XMPP SM)   feat: Add an endpointId field to StartEvent.   feat: Move jwt utils from jibri into jicoco-jwt.   chore: Update jitsi-metaconfig.   Add Java 21 to GitHub testing matrix   feat: Enables stream resumption.**

Enable XMPP stream resumption

---

pom.xml

A reconnect fix on startup a race may lead to keep trying to  reconnect filling up the logs with: WARNING: [25] [hostname=localhost id=shard] MucClient.lambda$getConnectAndLoginCallable$9#693: Error connecting: org.jivesoftware.smack.SmackException$AlreadyConnectedException: Client is already connected

chore: Updates jicoco.

---

jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/RtpLayerDesc.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/RtpReceiverImpl.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/RtpSender.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/RtpSenderImpl.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/Transceiver.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/rtp/RtpExtensions.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/transform/node/incoming/VlaReaderNode.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/transform/node/outgoing/HeaderExtStripper.kt
jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/BitrateController.kt
jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/SingleSourceAllocation.kt
jvb/src/main/kotlin/org/jitsi/videobridge/cc/config/BitrateControllerConfig.kt
jvb/src/main/kotlin/org/jitsi/videobridge/relay/Relay.kt
jvb/src/main/resources/reference.conf
rtp/src/main/kotlin/org/jitsi/rtp/rtp/header_extensions/VlaExtension.kt
rtp/src/main/kotlin/org/jitsi/rtp/util/BitReader.kt
rtp/src/test/kotlin/org/jitsi/rtp/extensions/VlaExtensionTest.kt
rtp/src/test/kotlin/org/jitsi/rtp/util/BitReaderTest.kt

- **feat: Add BitReader utilities and tests.**
- **feat: Add a parser for the VLA RTP header extension.**
- **ref: Remove unused function.**
- **feat: Update layers with info found in VLA.**
- **feat: Add an option to use targetBitrate instead of measured bitrate for allocation**

Add support for the VLA RTP header extension

---

CONFIG.md

Small PR - fixes the broken links in `CONFIG.md`.

fix: update broken links in `CONFIG.md`

---

jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/rtp/codec/av1/Av1DDRtpLayerDesc.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/rtp/codec/vpx/VpxRtpLayerDesc.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/transform/node/incoming/VlaReaderNode.kt
jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/BandwidthAllocator.kt
jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/BitrateController.kt
jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/SingleSourceAllocation.kt

Correctly calculate temporal layers' frame rates from VLA (presuming 2:1 ratios).

Handle the case where VLA-provided frame rate is less than the onstage preferred frame rate.

---

jvb/src/main/kotlin/org/jitsi/videobridge/cc/BandwidthProbing.kt
jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/BitrateController.kt

- **feat: Add stats for bandwidth probing to debug (rtcstats).**
- **fix: Use observed bitrate instead of encoder target when calculating probing needed.**

Add probing stats, try to fix probing rate

---

jvb/src/main/kotlin/org/jitsi/videobridge/Main.kt

Hello @bgrozev! I'm not really sure whether it is a typo or done on purpose but I noticed that during `VideobridgeExpireThread` move from `Videobridge` to `Main` in commit https://github.com/jitsi/jitsi-videobridge/commit/b623d6af714a17922750aa9d1c8060406ecb6e0a call to `VideobridgeExpireThread.start()` was lost.
Again, maybe it is done on purpose but in my deployment it leads to a weird situation that peers who lost connection are getting stuck in "reconnecting" state without being expired.

VideobridgeExpireThread is created but not started

---

jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/Prioritize.kt
jvb/src/test/kotlin/org/jitsi/videobridge/cc/allocation/EffectiveConstraintsTest.kt

- **fix: Sources with type NONE should not have effective constraints.**
- **squash: Adjust unit tests.**

fix: Sources with type NONE should not have effective constraints

---

debian/postinst
jvb/pom.xml

Remove Debian post-install logic that uses usrsctp on ppc64le.

Update dcsctp4j version.  Adds ppc64le support.

---

jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/format/PayloadType.kt
jvb/src/main/java/org/jitsi/videobridge/cc/AdaptiveSourceProjection.java
jvb/src/main/java/org/jitsi/videobridge/cc/AdaptiveSourceProjectionContext.java
jvb/src/main/kotlin/org/jitsi/videobridge/SsrcCache.kt
jvb/src/main/kotlin/org/jitsi/videobridge/cc/av1/Av1DDAdaptiveSourceProjectionContext.kt
jvb/src/main/kotlin/org/jitsi/videobridge/cc/av1/Av1DDFrameProjection.kt
jvb/src/main/kotlin/org/jitsi/videobridge/util/PayloadTypeUtil.kt
jvb/src/test/kotlin/org/jitsi/videobridge/cc/av1/Av1DDAdaptiveSourceProjectionTest.kt

Should work around Chrome issue when AV1 DDs are not sent for a source for some time, then resume.

Save persistent AV1 state

---

jvb/src/main/kotlin/org/jitsi/videobridge/relay/Relay.kt

This should run with web sockets as well.

fix: Schedule RelayMessageTransport timeout regardless of sctp config.

---

rtp/src/main/kotlin/org/jitsi/rtp/rtp/header_extensions/Av1DependencyDescriptorHeaderExtension.kt

(This is only used for debug output.)

Add activeDecodeTargets to AV1 DD JSON description

---

doc/debugging.md
doc/rest-colibri2.md

What are the things i have done in this pr: 
1) I removed the colibri1 (`/colibri/conferences` from debugging.md) - which is no more working (as we envision to `colibri2`) and also i checked it out into the colibri2(colibri/v2/conference) is not implemented [here](https://github.com/manzil-infinity180/jitsi-videobridge/blob/7cda0a6629fb266a397ab97d58d1bfd05626c8f0/jvb/src/main/java/org/jitsi/videobridge/rest/root/colibri/v2/conferences/Conferences.java#L41-L48)
2) Added the rest-colibri2.md (Similar to what we have in [rest-colibri.md](https://github.com/bgrozev/jitsi-videobridge/blob/master/doc/rest-colibri.md))

docs: removed the colibri1 from debugging and added rest-colibri2.md

---

jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/codec/vpx/PictureIdIndexTracker.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/rtp/ResumableStreamRewriter.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/rtp/TransportCcEngine.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/rtp/codec/av1/Av1DDParser.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/transform/node/incoming/TccGeneratorNode.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/transform/node/outgoing/TccSeqNumTagger.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/util/ArrayCache.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/util/Rfc3711IndexTracker.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/util/TreeCache.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/util/Util.kt
jitsi-media-transform/src/test/kotlin/org/jitsi/nlj/util/ArrayCacheTest.kt
jvb/src/main/java/org/jitsi/videobridge/cc/vp8/VP8FrameMap.java
jvb/src/main/kotlin/org/jitsi/videobridge/cc/av1/Av1DDAdaptiveSourceProjectionContext.kt
jvb/src/main/kotlin/org/jitsi/videobridge/cc/av1/Av1DDFrame.kt
jvb/src/main/kotlin/org/jitsi/videobridge/cc/av1/Av1DDFrameMap.kt
jvb/src/main/kotlin/org/jitsi/videobridge/cc/vp9/Vp9AdaptiveSourceProjectionContext.kt
jvb/src/main/kotlin/org/jitsi/videobridge/cc/vp9/Vp9Frame.kt
jvb/src/main/kotlin/org/jitsi/videobridge/cc/vp9/Vp9Picture.kt
jvb/src/main/kotlin/org/jitsi/videobridge/cc/vp9/Vp9PictureMap.kt
jvb/src/test/java/org/jitsi/videobridge/cc/vp8/VP8AdaptiveSourceProjectionTest.java
jvb/src/test/kotlin/org/jitsi/videobridge/cc/av1/Av1DDAdaptiveSourceProjectionTest.kt
jvb/src/test/kotlin/org/jitsi/videobridge/cc/av1/Av1DDQualityFilterTest.kt
jvb/src/test/kotlin/org/jitsi/videobridge/cc/vp9/Vp9AdaptiveSourceProjectionTest.kt
jvb/src/test/kotlin/org/jitsi/videobridge/cc/vp9/Vp9QualityFilterTest.kt

In a long-lived session, I'm pretty sure that extended sequence numbers can exceed an int, especially for transport sequence numbers (the most quickly-incrementing sequence number in our system).
In most cases the rollover will be fine, but there are some cases (e.g. `TccGeneratorNode`) where we compare extended sequence numbers numerically.

Compute and store extended sequence numbers as Long rather than Int.

---

doc/constraints.md
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/RtpLayerDesc.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/rtp/codec/av1/Av1DDPacket.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/rtp/codec/vp9/Vp9Packet.kt
jitsi-media-transform/src/main/kotlin/org/jitsi/nlj/transform/node/incoming/VlaReaderNode.kt
jitsi-media-transform/src/test/kotlin/org/jitsi/nlj/rtp/codec/av1/Av1DDPacketTest.kt
jitsi-media-transform/src/test/kotlin/org/jitsi/nlj/rtp/codec/vp9/Vp9PacketTest.kt

To handle portrait-mode video correctly.

Treat the minimum of a video frame's width or height as its height.
